In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Homework 1
## Data Tidying and Cleaning

In [3]:
# Reading the dataset... Naming it coffee_data
## The "../" helps referring to the parent folder of the current one.
coffee_data = pd.read_csv("../data/merged_data_cleaned.csv")

In [4]:
coffee_data

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334,1334,Robusta,luis robles,Ecuador,robustasa,Lavado 1,our own lab,NaN,robustasa,NaN,...,Blue-Green,1,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN
1335,1335,Robusta,luis robles,Ecuador,robustasa,Lavado 3,own laboratory,NaN,robustasa,40,...,Blue-Green,0,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,40.0,40.0,40.0
1336,1336,Robusta,james moore,United States,fazenda cazengo,NaN,cafe cazengo,NaN,global opportunity fund,795 meters,...,NaN,6,"December 23rd, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,795.0,795.0,795.0
1337,1337,Robusta,cafe politico,India,NaN,NaN,NaN,14-1118-2014-0087,cafe politico,NaN,...,Green,1,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN
1338,1338,Robusta,cafe politico,Vietnam,NaN,NaN,NaN,NaN,cafe politico,NaN,...,NaN,9,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN

In [5]:
# Size of the dataset
coffee_data.shape

(1339, 44)

In [6]:
# Columns (variables / features) in the dataset
coffee_data.columns

Index(['Unnamed: 0', 'Species', 'Owner', 'Country.of.Origin', 'Farm.Name',
       'Lot.Number', 'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region',
       'Producer', 'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner',
       'Harvest.Year', 'Grading.Date', 'Owner.1', 'Variety',
       'Processing.Method', 'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body',
       'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points',
       'Total.Cup.Points', 'Moisture', 'Category.One.Defects', 'Quakers',
       'Color', 'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [7]:
# Types of variables
coffee_data.dtypes

Unnamed: 0                 int64
Species                   object
Owner                     object
Country.of.Origin         object
Farm.Name                 object
Lot.Number                object
Mill                      object
ICO.Number                object
Company                   object
Altitude                  object
Region                    object
Producer                  object
Number.of.Bags             int64
Bag.Weight                object
In.Country.Partner        object
Harvest.Year              object
Grading.Date              object
Owner.1                   object
Variety                   object
Processing.Method         object
Aroma                    float64
Flavor                   float64
Aftertaste               float64
Acidity                  float64
Body                     float64
Balance                  float64
Uniformity               float64
Clean.Cup                float64
Sweetness                float64
Cupper.Points            float64
Total.Cup.Points         float64
Moisture                 float64
Category.One.Defects       int64
Quakers                  float64
Color                     object
Category.Two.Defects       int64
Expiration                object
Certification.Body        object
Certification.Address     object
Certification.Contact     object
unit_of_measurement       object
altitude_low_meters      float64
altitude_high_meters     float64
altitude_mean_meters     float64
dtype: object

In [8]:
# Checking if the column "Unnamed: 0" is the same as the "index" column
coffee_data["Unnamed: 0"].nunique()

1339

In [9]:
# Remove the unnecessary column ["Unnamed: 0"] as it is the same as the index 
# (proven by the previous row - we have 1339 unique values which is exactly the role of the index)
coffee_data = coffee_data.drop(columns = "Unnamed: 0")

In [10]:
coffee_data.columns

Index(['Species', 'Owner', 'Country.of.Origin', 'Farm.Name', 'Lot.Number',
       'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner', 'Harvest.Year',
       'Grading.Date', 'Owner.1', 'Variety', 'Processing.Method', 'Aroma',
       'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity',
       'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Total.Cup.Points',
       'Moisture', 'Category.One.Defects', 'Quakers', 'Color',
       'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [11]:
# See if Species can be turned into a categorical variable instead of being an object var
coffee_data.Species

0       Arabica
1       Arabica
2       Arabica
3       Arabica
4       Arabica
         ...
1334    Robusta
1335    Robusta
1336    Robusta
1337    Robusta
1338    Robusta
Name: Species, Length: 1339, dtype: object

In [12]:
coffee_data.Species.value_counts(dropna = False)

Species
Arabica    1311
Robusta      28
Name: count, dtype: int64

In [13]:
# As there are only two types of coffee species, the feature "species" can be turned into a categorical variable
coffee_data.Species = coffee_data.Species.astype("category")

In [14]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Species                1339 non-null   category
 1   Owner                  1332 non-null   object
 2   Country.of.Origin      1338 non-null   object
 3   Farm.Name              980 non-null    object
 4   Lot.Number             276 non-null    object
 5   Mill                   1021 non-null   object
 6   ICO.Number             1180 non-null   object
 7   Company                1130 non-null   object
 8   Altitude               1113 non-null   object
 9   Region                 1280 non-null   object
 10  Producer               1107 non-null   object
 11  Number.of.Bags         1339 non-null   int64
 12  Bag.Weight             1339 non-null   object
 13  In.Country.Partner     1339 non-null   object
 14  Harvest.Year           1292 non-null   object
 15  Grading.Date           1339 non-null   object
 16  Owner.1                1332 non-null   object
 17  Variety                1113 non-null   object
 18  Processing.Method      1169 non-null   object
 19  Aroma                  1339 non-null   float64
 20  Flavor                 1339 non-null   float64
 21  Aftertaste             1339 non-null   float64
 22  Acidity                1339 non-null   float64
 23  Body                   1339 non-null   float64
 24  Balance                1339 non-null   float64
 25  Uniformity             1339 non-null   float64
 26  Clean.Cup              1339 non-null   float64
 27  Sweetness              1339 non-null   float64
 28  Cupper.Points          1339 non-null   float64
 29  Total.Cup.Points       1339 non-null   float64
 30  Moisture               1339 non-null   float64
 31  Category.One.Defects   1339 non-null   int64
 32  Quakers                1338 non-null   float64
 33  Color                  1069 non-null   object
 34  Category.Two.Defects   1339 non-null   int64
 35  Expiration             1339 non-null   object
 36  Certification.Body     1339 non-null   object
 37  Certification.Address  1339 non-null   object
 38  Certification.Contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(23)
memory usage: 440.9+ KB

In [15]:
# Make the columns in a more pythonic style
coffee_data.columns = coffee_data.columns.str.lower()

In [16]:
coffee_data = coffee_data.rename(columns = lambda col: col.replace(".", "_"))

In [17]:
coffee_data.species.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1339 entries, 0 to 1338
Series name: species
Non-Null Count  Dtype
--------------  -----
1339 non-null   category
dtypes: category(1)
memory usage: 1.6 KB

In [18]:
coffee_data.columns

Index(['species', 'owner', 'country_of_origin', 'farm_name', 'lot_number',
       'mill', 'ico_number', 'company', 'altitude', 'region', 'producer',
       'number_of_bags', 'bag_weight', 'in_country_partner', 'harvest_year',
       'grading_date', 'owner_1', 'variety', 'processing_method', 'aroma',
       'flavor', 'aftertaste', 'acidity', 'body', 'balance', 'uniformity',
       'clean_cup', 'sweetness', 'cupper_points', 'total_cup_points',
       'moisture', 'category_one_defects', 'quakers', 'color',
       'category_two_defects', 'expiration', 'certification_body',
       'certification_address', 'certification_contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [19]:
coffee_data.owner

0                      metad plc
1                      metad plc
2       grounds for health admin
3            yidnekachew dabessa
4                      metad plc
                  ...
1334                 luis robles
1335                 luis robles
1336                 james moore
1337               cafe politico
1338               cafe politico
Name: owner, Length: 1339, dtype: object

In [20]:
# View the owners and how many times they appear in the dataset
coffee_data.owner.value_counts(dropna = False)

owner
juan luis alvarado romero            155
racafe & cia s.c.a                    60
exportadora de cafe condor s.a        54
kona pacific farmers cooperative      52
ipanema coffees                       50
                                    ...
kasozi coffee farmers association      1
nitubaasa ltd                          1
mannya coffee project                  1
yidnekachew dabessa                    1
james moore                            1
Name: count, Length: 316, dtype: int64

In [21]:
# It is better to upper their names
coffee_data.owner = coffee_data.owner.str.upper()

In [22]:
coffee_data.owner

coffee_data.owner.unique()

array(['METAD PLC', 'GROUNDS FOR HEALTH ADMIN', 'YIDNEKACHEW DABESSA',
       'JI-AE AHN', 'HUGO VALDIVIA', 'ETHIOPIA COMMODITY EXCHANGE',
       'DIAMOND ENTERPRISE PLC', 'MOHAMMED LALO',
       'CQI Q COFFEE SAMPLE REPRESENTATIVE', 'YUNNAN COFFEE EXCHANGE',
       'ESSENCECOFFEE', 'THE COFFEE SOURCE INC.', 'ROBERTO LICONA FRANCO',
       'NUCOFFEE', 'KABUM TRADING COMPANY', 'BISMARCK CASTRO',
       'LIN, CHE-HAO KRUDE 林哲豪', 'NORA ZEAS', 'SPECIALTY COFFEE-KOREA',
       'FRANCISCO A MENA', 'HIDER ABAMECHA', 'DANIEL MAGU',
       'KONA PACIFIC FARMERS COOPERATIVE', 'ITDP INTERNATIONAL',
       'JACQUES PEREIRA CARNEIRO', 'JUNGLE ESTATE',
       'GREAT LAKES COFFEE UGANDA', 'LUSSO LAB', 'AFCA',
       'JUAN LUIS ALVARADO ROMERO', 'KAWACOM UGANDA LTD',
       'EXPORTADORA DE CAFE CONDOR S.A', 'GONZALO HERNANDEZ',
       'IBRAHIM HUSSIEN SPECIALITY COFFEE PRODUCER &EXPORT',
       'SEID DAMTEW COFFEE PLANATAION', 'DANE LORAAS',
       'COLBRAN COFFEELANDS, LTD.', 'ATLANTIC SPECIALTY COFFEE',
       'ASSEFA BELAY COFFEE PRODUCER', 'KYAGALANYI LTD',
       'RASHID MOLEDINA & CO. (MSA) LTD.', 'IBERO KENYA LIMITED',
       'COMPAÑIA COLOMBIANA AGROINDUSTRIAL S.A',
       'NOMURA TRADING CO., LTD.', 'CARCAFE LTDA CI', 'STEVEN KIL',
       'EILEEN KOYANAGI', 'KYAGALANYI COFFEE LTD', 'RACAFE & CIA S.C.A',
       'TROY QUIMBY', 'EL EQUIMITE, CAFETAL BIODINÁMICO', 'SIMON MAHINDA',
       'YOUNG KIM', 'CARL WALKER', 'TAYLOR WINCH (T) LTD',
       'ARTEMIO ZAPATA TEJEDA', 'BRIAN SPECKMAN', 'PHILIP SCHLUTER',
       '松澤宏樹 KOJU MATSUZAWA', 'LYDIAH MWANGI', 'CADEXSA',
       'CONSEJO SALVADOREÑO DEL CAFÉ', 'SANJAVA COFFEE', 'RODRIGO SOTO',
       'FABIAN CALDERON MORA', 'ERIC THORMAEHLEN', 'ROB TUTTLE',
       'CQI TAIWAN ICP CQI台灣合作夥伴', 'DREAM TOGETHER',
       'ORGANIZACIONES DE PRODUCTORES DE CAFE COLIMENSE',
       'BENJAMIN SCHMERLER', 'TAYLOR WINCH (COFFEE) LTD.', 'MAX GURDIAN',
       'ECOM JAPAN LIMITED', 'FEDERACION NACIONAL DE CAFETEROS',
       'ERIC WU', 'MARIA IMELDA USCANGA MARTINEZ', 'ALFREDO BOJALIL',
       'DANIEL FRIEDLANDER', 'ALEXANDRA KATONA-CARROLL',
       'AULIA ARIF SYAHRI', 'KAO MING LEE',
       'MARIA AMALIA GUADALUPE TORIELLO ELORZA', 'RAÚL VARGAS',
       'VICTOR HUGO MELCHOR CORDOVA', 'TEMBO COFFEE COMPANY LTD',
       'JESUS SALAZAR VELASCO', 'MANUEL HERRERA JUAREZ', 'WAYNER JIMENEZ',
       'COOPERATIVA EL GORRION R.L', 'CAFEBRAS', 'CECA, S.A.',
       'ASEFA DUKAMO KEROMA', 'SELIAN COFFEE ESTATE',
       'OLAM AGRO COLOMBIA', 'CHRIS FINCH', 'ITOCHU CORPORATION',
       'OWEN CARVER', 'PT.ROYAL PACIFIC INDAH INTERNATIONAL',
       'ANDRES MARTINEZ LEON', 'AMANDA POWERS', 'IPANEMA COFFEES',
       'DOI TUNG DEVELOPMENT PROJECT', 'CAFES TOMARI SA DE CV',
       'SARAWUT PREMJIT', 'ALMACAFE', 'OSCAR ORTEGA CARBALLO',
       'YASMIN COFFFEE PLANTATION PLC', 'GARET ALBAN',
       'FILEMON MENDOZA CAMPOS', 'DOI CHAANG COFFEE COMPANY',
       'KENNEDY MACHARIA', 'NILE HIGHLAND ARABICA COFFEE FARMERS',
       'GERMAN NEGRON', 'SAUL M. HERNANDEZ RAMIREZ',
       'COMERCIAL INTERNACIONAL EXPORTADORA, S.A.', 'ROB STEPHEN',
       'JUAN LUIS ORTEGA CARBALLO', 'EKAI INTERNATIONAL COMPANY LTD.',
       'ANDREAS KUSSMAUL', 'BULAMBURI COFFEE FARMERS ASSOCIATION',
       'DAMARI ABSALOME', 'DEBESA AGRO INDUSTRY PLC', nan,
       'MIGUEL CORTES MORENO', 'GABRIEL BERNARDO RIVAS ROSS',
       'FELIPE ISAZA', 'SPECIALTY COFFEE ASSOCIATION OF INDONESIA',
       'BUGISU COOPERATIVE UNION', 'BOURBON SPECIALTY COFFEES',
       'NGILA ESTATE LTD', 'J.ANDRADE', 'ITIAH COFFEE LLC',
       'CAFE DE DON BALBINO S.C. DE R.L. DE C.V.',
       'PRODUCTOS Y SERVICIOS CHILINDRON S.A. DE C.V.',
       'CALIXTO GUILLEN VAZQUEZ', 'ERNESTO RODRIGUEZ LUNA',
       'MODESTO LANDEROS FLORES', 'ANDREA BERNAL', 'SUNVIRTUE CO., LTD.',
       'TUTUNZE KAHAWA LTD', 'CAFE POLITICO', 'MAYRA YESSENIA TORRES',
       'BALAM HINYULA', 'NESTOR MENDEZ GOMEZ',
       'FERNANDO MENDOZA APARICIO',
       'MARIA LUISA DEL CARMEN ROJAS NARVAEZ', 'UCFA',
       'IRENE ALVES SANTOS', 'STAR CAFE LTD',
       'ROSA AURORA FALCON FERNANDEZ', 'SANTIAGO SOLIS AYERDI',
       'RENEE A. PERRINE', 'ZARAH ZAMORA PEREZ', 'ANDREW BOWMAN',
       'EXPOCACCER COOP DOS CAFEIC DO CERRADO LTDA',
       'NYAPEA COFFEE FARMERS ASSOCIATION', 'MARIA GUADALUPE GOMEZ ANZO',
       'ROYAL BASE CORPORATION', 'VERONICA LOPEZ CASTILLEJOS',
       'SAMUEL MUHIRWA', 'JOSHUA MARSCEAU', 'COFFEEBYTHEBAG.COM , INC',
       'EDWIN AGASSO', 'ARMANDO LUIS POHLENZ MARTINEZ', 'COFFEE EXPORT',
       'SERGIO DE LA VEQUIA BERNARDI', 'ROMULO BELLO FLORES',
       'RACHEL PETERSON', 'JOSÉ LUIS ROJAS YEO', 'NITIN COFFEE ESTATE',
       'ADAM KLINE', 'MONTEGRANDE',
       'GRUPO CAFETALERO LOS BRUJOS SPR DE RL', 'GEORGE A. FERNANDEZ',
       'GABRIEL BARBARA', 'ANDRY SIMARMATA', 'BRENT HALL',
       'GUILLERMO ROJAS SALDANA', 'ELSY REYES', 'SHAH PLANTATIONS',
       'AMKENI GOURMET COFFEE GROUP', 'ENRIQUE MITRE LOPEZ',
       'ENRIQUE EDUARDO LOPEZ AGUILAR', 'BRIAN BECK',
       'GLADNESS OBED PALLANGYO', 'DARIO CESAR GALEANA SANCHEZ',
       'JOSE DANIEL COBILT CASTRO', 'ALVARO QUIROS PEREZ',
       'OLIVIA HERNANDEZ VIRVES', 'FINCA LAS NIEVES',
       'PEDRO SANTOS E SILVA', 'MICHAEL GAVINA', 'KLEM ORGANICS',
       'JESUS CARLOS CARDENAS VALDIVIA', 'BENCAFE, S. A.',
       'LANGIRO FARM GROUP', 'IBERO COFFEE TRADING CO (T) LTD',
       'SALVADOR CARO CARRION', 'CAFETALERA INTERNACIONAL CAFINTER, S.A.',
       'NGOROGORO CONVENANT ESTATE', 'JULIO PEREZ HERNANDEZ', 'DIDAS',
       'MINWOOK KU', 'FINCA ESTATE', 'BENEFICIO SANTA ROSA',
       'JORGE OCTAVIO ESCAMILLA PRADO', 'MCOMAFA CO LTD',
       'JUAN HERMILIO SAMPIERI CARCAMO', 'U MG MG', 'VIRIDIANA',
       'KURT KAPPELI', 'CHRISTINA DUSING',
       'JORGE FRANCISCO MARTINEZ HACHITY', 'SERGIO LANDA ALARCON',
       'DIEGO MANUEL WOOLRICH RAMIREZ', 'DAE LTD COMPANY',
       'FREDY GORDILLO REYES', 'VIRGINIA GORDILLO GORDILLO',
       'JOSE LUIS MUNOZ GUERRERO', 'MDH', 'ACACIA HILLS LTD',
       'EXPORTADORA ATLANTIC, S.A.', 'GENIUS COFFEE',
       'SANTA LAURA EXPORTADORA DE CAFE S.L.E.C. S.A.',
       'MYRIAM KAPLAN-PASTERNAK', 'TOMAS EDELMANN BLASS',
       'MARIA DE LA PAZ AGUILAR GUILLEN', 'ANGEL OSCAR MEDINA RODRIGUEZ',
       'VICTORIA', 'HECTOR GABRIEL BARREDA NADER',
       'SHANGRILLA ESTATE LTD', 'IMMACULATA JOHN', 'KERCHANSHE',
       'GREGORIO SEBBA', 'ROLANDO LACAYO', 'WALI ALI',
       'OBED RENDON PONCE', 'GERARDO HERNANDEZ VALDERRABANO',
       'BALBINO RAMIREZ FLORES', 'MLIMANI NGARASHI',
       'ALEJANDRO GARCIA PALACIOS', 'GRUPO SANTAB S.A DE C.V.',
       'MIN HLAING', 'KARATU ESTATE',
       'EDUARDO LUIS AUGUSTO VELAZQUEZ SOLIS',
       'LUIS ROBERTO FERMOSO BELTRAN', 'JOSE MANUEL VERGARA CORTES',
       'U SOE', 'BURKA COFFEE ESTATE', 'JANNY MARLITH TORRES',
       'CASE NOYALE LTD', 'SHWE YIN MAR COFFEE',
       'ISRAEL EDUARDO PAZ GARCIA', 'ADAM CIRULI YE',
       'DELFINA LEON SHINE', 'KONGONI ESTATE', 'VOLCAFE LTDA. - BRASIL',
       'BOB MCCAULEY', 'U HTUN HTUN', 'GLORIA ANTONIETA ESCOBAR URRUTIA',
       'HONOR DELA FUENTE', 'PABLO ENRIQUE MARTINEZ GAMA',
       'MARCO VIRGILIO RAMIREZ TELIZ', 'BRAYAN CUNHA SOUZA',
       'FEDERICO PACHECO PEREZ', 'NGU SHWE LI',
       'SEMIRAMIS CASAS VELAZQUEZ', 'JESUS CARLOS CADENA VALDIVIA',
       'ASOCIACIÓN ALDEA GLOBAL JINOTEGA', 'LEONIDES DE LA CRUZ LOPEZ',
       'MARIO JOSE FERNANDEZ', 'ADRIANA TORRES RICO QUEVEDO',
       'RRE KUNENE', 'ERIC JESUS CORDOBA ARROYO',
       'JULIO CESAR ROBLES FLORES', 'MASAMICHI HIROIKE',
       'JUANA RODRIGUEZ GUTIERREZ',
       'CAFES FINOS DE EXPORTACION S DE R.L.',
       'SUSTAINABLE HARVEST COFFEE', 'GONZALO DE AQUINO FLORES',
       'JUAN AVENAMAR RODRIGUEZ FUNEZ', 'OCTAVIO AUGUSTO DIAZ TREJO',
       'DAMASO MARTINEZ PEREZ',
       'PRODUCTORES DE ESPECIALIDAD EMILIANO ZAPEATA, SPR.',
       'JUAN GARCIA HERNANDEZ', 'ROSARIO MIGUEL HERNANDEZ',
       'FRANCISCO RUIZ NUNEZ', 'PABLO CERVANTES MORELOS        ',
       'GUSTAVO AMIEVA GONZALEZ', 'SAMUEL ELI GUREL', 'MAO-HENG CHU',
       'GUSTAVO ABARCA SOLIS', 'STEPHANY ESCAMILLA FEMAT',
       'HOMERO ANTONIO DE ANDA ANDRADE', 'WILLIAM HO',
       'GUILLERMO EDUARDO BOBADILLA MUGUIRA', 'ANA GONZALES',
       'FRANCISCO HERNANDEZ LORENZO', 'MARTIN JIMENEZ CASIANO',
       'GRUPO JUVENIL MAGTAYANI, AC', 'MYRNA ROXANA GALVEZ GONZALEZ',
       'EUGENE HOLMAN PEW', 'JOSE ARMANDO NORBERTO BORZANI LEMINI',
       'RICARDO AARON SAMPIERI MARINI', 'JUAN CARLOS GARCIA LOPEZ',
       'ANKOLE COFFEE PRODUCERS COOP', 'NISHANT GURJER', 'ANDREW HETZEL',
       'UGACOF', 'KATUKA DEVELOPMENT TRUST LTD',
       'KASOZI COFFEE FARMERS ASSOCIATION', 'NITUBAASA LTD',
       'MANNYA COFFEE PROJECT', 'LUIS ROBLES', 'JAMES MOORE'],
      dtype=object)

In [23]:
# These are the records that do not have an owner but I spot something else here.
## A lot of records have a duplicate but with some little differences which come from the ico_number
coffee_data[coffee_data.owner.isna() == True]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
364,Arabica,NaN,Honduras,los hicaques,NaN,cigrah sps,13-111-240,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
459,Arabica,NaN,Honduras,los hicaques,NaN,cigrah sps,13-111-193,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
602,Arabica,NaN,Colombia,supply chain ecom cca s.a.,NaN,south huila,3-79-0334,ecom cca s.a.,1400 thru 1850,south huila,...,Blue-Green,0,"April 11th, 2013",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,1400.0,1850.0,1625.0
848,Arabica,NaN,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-311,cigrah,1350,comayagua,...,Green,4,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
882,Arabica,NaN,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-192,cigrah,1400,comayagua,...,Green,5,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.0,1400.0,1400.0
975,Arabica,NaN,Honduras,los hicaques,NaN,cigrah,13-111-037,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0
1044,Arabica,NaN,Honduras,los hicaques,NaN,cigrah,13-111-035,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0

In [24]:
coffee_data[["owner", "farm_name"]].sample(20)

,owner,farm_name
667,ENRIQUE MITRE LOPEZ,caltuchoco
347,RACAFE & CIA S.C.A,NaN
294,ETHIOPIA COMMODITY EXCHANGE,"phone number | 0911-51-08-01, email | at"
150,COMPAÑIA COLOMBIANA AGROINDUSTRIAL S.A,NaN
607,IPANEMA COFFEES,capoeirinha
35,DANIEL MAGU,kangunu
99,"EL EQUIMITE, CAFETAL BIODINÁMICO",various
546,JUAN LUIS ALVARADO ROMERO,finca medina
1323,ANDREW HETZEL,sethuraman estates
514,EXPORTADORA DE CAFE CONDOR S.A,NaN
497,IPANEMA COFFEES,fazenda capoeirnha
752,EXPORTADORA DE CAFE CONDOR S.A,NaN
710,RODRIGO SOTO,rio jorco
87,THE COFFEE SOURCE INC.,coop. hoja blanca - fedecocagua
961,KLEM ORGANICS,fazendas klem ltda
281,YASMIN COFFFEE PLANTATION PLC,NaN
904,FREDY GORDILLO REYES,union ramal santa cruz
340,ANDREAS KUSSMAUL,exportadora café california
479,RACAFE & CIA S.C.A,NaN
1073,SHWE YIN MAR COFFEE,mixed

In [25]:
# As I do not known the owner, I think that the best option is to replace the NaN values with "Unknown".
# According to my research, some coffee brands do not have an exact owner such as the coffee from Honduras - 
# actually there is no farm Ios Hicaques because that is a coffee-producing region in Honduras
coffee_data.owner = coffee_data.owner.fillna("Unknown")

In [26]:
coffee_data[coffee_data.owner == "Unknown"]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
364,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah sps,13-111-240,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
459,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah sps,13-111-193,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
602,Arabica,Unknown,Colombia,supply chain ecom cca s.a.,NaN,south huila,3-79-0334,ecom cca s.a.,1400 thru 1850,south huila,...,Blue-Green,0,"April 11th, 2013",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,1400.0,1850.0,1625.0
848,Arabica,Unknown,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-311,cigrah,1350,comayagua,...,Green,4,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
882,Arabica,Unknown,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-192,cigrah,1400,comayagua,...,Green,5,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.0,1400.0,1400.0
975,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah,13-111-037,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0
1044,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah,13-111-035,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0

In [27]:
coffee_data["country_of_origin"].value_counts(dropna = False)

country_of_origin
Mexico                          236
Colombia                        183
Guatemala                       181
Brazil                          132
Taiwan                           75
United States (Hawaii)           73
Honduras                         53
Costa Rica                       51
Ethiopia                         44
Tanzania, United Republic Of     40
Uganda                           36
Thailand                         32
Nicaragua                        26
Kenya                            25
El Salvador                      21
Indonesia                        20
China                            16
India                            14
Malawi                           11
United States                    10
Peru                             10
Vietnam                           8
Myanmar                           8
Haiti                             6
Philippines                       5
United States (Puerto Rico)       4
Panama                            4
Laos                              3
Ecuador                           3
Burundi                           2
Papua New Guinea                  1
Rwanda                            1
Japan                             1
Zambia                            1
Mauritius                         1
Cote d?Ivoire                     1
NaN                               1
Name: count, dtype: int64

In [28]:
coffee_data[coffee_data["country_of_origin"].isna()]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1197,Arabica,RACAFE & CIA S.C.A,NaN,NaN,NaN,NaN,3-37-1980,NaN,NaN,NaN,...,NaN,3,"February 29th, 2012",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,NaN,NaN,NaN

In [29]:
# The country which is missing is Columbia according to my research
# source = "http://racafe.com.co/en/about-us/about-racafe/"
coffee_data["country_of_origin"] = coffee_data["country_of_origin"].fillna("Colombia")

In [30]:
coffee_data.loc[1197]

species                                                   Arabica
owner                                          RACAFE & CIA S.C.A
country_of_origin                                        Colombia
farm_name                                                     NaN
lot_number                                                    NaN
mill                                                          NaN
ico_number                                              3-37-1980
company                                                       NaN
altitude                                                      NaN
region                                                        NaN
producer                                                      NaN
number_of_bags                                                149
bag_weight                                                  70 kg
in_country_partner                                       Almacafé
harvest_year                                                  NaN
grading_date                                      March 1st, 2011
owner_1                                        Racafe & Cia S.C.A
variety                                                       NaN
processing_method                                             NaN
aroma                                                        6.75
flavor                                                       6.75
aftertaste                                                   6.42
acidity                                                      6.83
body                                                         7.58
balance                                                       7.5
uniformity                                                   10.0
clean_cup                                                    10.0
sweetness                                                    10.0
cupper_points                                                7.25
total_cup_points                                            79.08
moisture                                                      0.1
category_one_defects                                            0
quakers                                                       0.0
color                                                         NaN
category_two_defects                                            3
expiration                                    February 29th, 2012
certification_body                                       Almacafé
certification_address    e493c36c2d076bf273064f7ac23ad562af257a25
certification_contact    70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab
unit_of_measurement                                             m
altitude_low_meters                                           NaN
altitude_high_meters                                          NaN
altitude_mean_meters                                          NaN
Name: 1197, dtype: object

In [31]:
# I also spotted some errors in two other names - Côte d'Ivoire, and "Tanzania, United Republic of" is a little bit bland.

country_replacements = {
    "Tanzania, United Republic Of": "Tanzania",
    "Cote d?Ivoire": "Côte d'Ivoire"
}

coffee_data["country_of_origin"] = coffee_data['country_of_origin'].replace(country_replacements)

In [32]:
coffee_data["country_of_origin"].value_counts(dropna = False)

country_of_origin
Mexico                         236
Colombia                       184
Guatemala                      181
Brazil                         132
Taiwan                          75
United States (Hawaii)          73
Honduras                        53
Costa Rica                      51
Ethiopia                        44
Tanzania                        40
Uganda                          36
Thailand                        32
Nicaragua                       26
Kenya                           25
El Salvador                     21
Indonesia                       20
China                           16
India                           14
Malawi                          11
Peru                            10
United States                   10
Vietnam                          8
Myanmar                          8
Haiti                            6
Philippines                      5
Panama                           4
United States (Puerto Rico)      4
Ecuador                          3
Laos                             3
Burundi                          2
Papua New Guinea                 1
Japan                            1
Zambia                           1
Rwanda                           1
Mauritius                        1
Côte d'Ivoire                    1
Name: count, dtype: int64

In [33]:
# Now I move on to the next column which is farm_name
coffee_data["farm_name"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1339 entries, 0 to 1338
Series name: farm_name
Non-Null Count  Dtype
--------------  -----
980 non-null    object
dtypes: object(1)
memory usage: 10.6+ KB

In [34]:
# There are 359 NaN values in the "farm_name" column.
# That is why I will replace with "Unspecified"
1339 - 980

359

In [35]:
coffee_data["farm_name"] = coffee_data["farm_name"].fillna("Unspecified")

In [36]:
coffee_data["farm_name"] == "Unspecified").value_counts()

farm_name
False    980
True     359
Name: count, dtype: int64

In [75]:
coffee_data.loc[coffee_data["farm_name"] != "Unspecified", "farm_name"] = coffee_data.loc[coffee_data["farm_name"] != "Unspecified", "farm_name"].str.capitalize()

In [76]:
coffee_data["farm_name"].value_counts(dropna = False)

farm_name
Unspecified                               359
Various                                    47
Rio verde                                  23
Several                                    20
Finca medina                               15
                                         ...
Producer group (approx. 1,000 farmers)      1
Finca la fortuna                            1
Cofradia                                    1
Las ceibas                                  1
Sierra madre                                1
Name: count, Length: 572, dtype: int64

In [37]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   species                1339 non-null   category
 1   owner                  1339 non-null   object
 2   country_of_origin      1339 non-null   object
 3   farm_name              1339 non-null   object
 4   lot_number             276 non-null    object
 5   mill                   1021 non-null   object
 6   ico_number             1180 non-null   object
 7   company                1130 non-null   object
 8   altitude               1113 non-null   object
 9   region                 1280 non-null   object
 10  producer               1107 non-null   object
 11  number_of_bags         1339 non-null   int64
 12  bag_weight             1339 non-null   object
 13  in_country_partner     1339 non-null   object
 14  harvest_year           1292 non-null   object
 15  grading_date           1339 non-null   object
 16  owner_1                1332 non-null   object
 17  variety                1113 non-null   object
 18  processing_method      1169 non-null   object
 19  aroma                  1339 non-null   float64
 20  flavor                 1339 non-null   float64
 21  aftertaste             1339 non-null   float64
 22  acidity                1339 non-null   float64
 23  body                   1339 non-null   float64
 24  balance                1339 non-null   float64
 25  uniformity             1339 non-null   float64
 26  clean_cup              1339 non-null   float64
 27  sweetness              1339 non-null   float64
 28  cupper_points          1339 non-null   float64
 29  total_cup_points       1339 non-null   float64
 30  moisture               1339 non-null   float64
 31  category_one_defects   1339 non-null   int64
 32  quakers                1338 non-null   float64
 33  color                  1069 non-null   object
 34  category_two_defects   1339 non-null   int64
 35  expiration             1339 non-null   object
 36  certification_body     1339 non-null   object
 37  certification_address  1339 non-null   object
 38  certification_contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(23)
memory usage: 440.9+ KB

In [38]:
# The lot_number has only 276 not Nan values which means that it is not a vital variable for analysis.
# That is why I think it will be better to remove it
coffee_data["lot_number"].value_counts(dropna = False)

lot_number
NaN         1063
1             18
020/17         6
019/17         5
2              3
            ...
7              1
RKR            1
RC AB          1
Lavado 1       1
Lavado 3       1
Name: count, Length: 228, dtype: int64

In [39]:
coffee_data["lot_number"].nunique()

227

In [40]:
coffee_data['lot_number'].notna().sum() / len(coffee_data) * 100

np.float64(20.612397311426438)

In [41]:
# As only 20% of the data have lot numbers, we can drop this column.
# Moreover, it is not useful for the purpose of analysis
coffee_data = coffee_data.drop(columns = ["lot_number"])

In [42]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   species                1339 non-null   category
 1   owner                  1339 non-null   object
 2   country_of_origin      1339 non-null   object
 3   farm_name              1339 non-null   object
 4   mill                   1021 non-null   object
 5   ico_number             1180 non-null   object
 6   company                1130 non-null   object
 7   altitude               1113 non-null   object
 8   region                 1280 non-null   object
 9   producer               1107 non-null   object
 10  number_of_bags         1339 non-null   int64
 11  bag_weight             1339 non-null   object
 12  in_country_partner     1339 non-null   object
 13  harvest_year           1292 non-null   object
 14  grading_date           1339 non-null   object
 15  owner_1                1332 non-null   object
 16  variety                1113 non-null   object
 17  processing_method      1169 non-null   object
 18  aroma                  1339 non-null   float64
 19  flavor                 1339 non-null   float64
 20  aftertaste             1339 non-null   float64
 21  acidity                1339 non-null   float64
 22  body                   1339 non-null   float64
 23  balance                1339 non-null   float64
 24  uniformity             1339 non-null   float64
 25  clean_cup              1339 non-null   float64
 26  sweetness              1339 non-null   float64
 27  cupper_points          1339 non-null   float64
 28  total_cup_points       1339 non-null   float64
 29  moisture               1339 non-null   float64
 30  category_one_defects   1339 non-null   int64
 31  quakers                1338 non-null   float64
 32  color                  1069 non-null   object
 33  category_two_defects   1339 non-null   int64
 34  expiration             1339 non-null   object
 35  certification_body     1339 non-null   object
 36  certification_address  1339 non-null   object
 37  certification_contact  1339 non-null   object
 38  unit_of_measurement    1339 non-null   object
 39  altitude_low_meters    1109 non-null   float64
 40  altitude_high_meters   1109 non-null   float64
 41  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(22)
memory usage: 430.5+ KB

In [43]:
coffee_data.mill.value_counts(dropna = False)

mill
NaN                                                     318
beneficio ixchel                                         90
dry mill                                                 39
trilladora boananza                                      38
ipanema coffees                                          16
                                                       ...
las minas                                                 1
la distancia                                              1
coeb koperativ ekselsyo basen (350 members)               1
la esperanza, municipio juchique de ferrer, veracruz      1
wolensu                                                   1
Name: count, Length: 460, dtype: int64

In [44]:
coffee_data.mill = coffee_data.mill.fillna("Unknown")

In [45]:
coffee_data.loc[coffee_data.mill != "Unknown", "mill"] = coffee_data.loc[coffee_data.mill != "Unknown", "mill"].str.upper()

In [46]:
# Now let's look at the ico_number
# We have NaN values again
coffee_data["ico_number"].value_counts(dropna = False)

ico_number
NaN               159
0                  77
Taiwan             31
2222               11
-                   9
                 ...
1104820070          1
220456              1
0016-2722-0001      1
5-545-0015          1
11111               1
Name: count, Length: 847, dtype: int64

In [47]:
coffee_data["ico_number"].info()
# 152 records do not have values

<class 'pandas.core.series.Series'>
RangeIndex: 1339 entries, 0 to 1338
Series name: ico_number
Non-Null Count  Dtype
--------------  -----
1180 non-null   object
dtypes: object(1)
memory usage: 10.6+ KB

In [48]:
coffee_data["ico_number"].unique()

array(['2014/2015', nan, '010/0338', '2014/15', 'unknown', '010/0056',
       '100181006', '5-562-0015', '0', '002/1251/0073', '010/0056/Sidamo',
       '13-111-053', 'Taiwan', '790-0013', 'A019116', '002/1251/0068',
       '5818009', '220452', 'HDOA 210128 Kona Fancy', '010/0170',
       '01-011-512', '002/1352/0045', 'NIL', '002/1251/0071', 'NONE', 'x',
       '010/0145', '11/23/0252', '3-68-0215', '11/1886/03', '11-853-155',
       '490', '030-0537-2066', '25072012', '09 – 060-24', '220451',
       '290503', '3707361715', '2015', '11-52-492', '220453',
       '002/1251/0072', '9-060-60D-L-1D', '11999144', '5-562-0006',
       '5-562-0016', '37/672/0017', '37/00597/0252 - AB FAQ Q certified',
       '010/0157', '010/0001/0022', '11/23/0177', '3-68-0102',
       '3-79-0634', '11-30-0593', '495', '3-59-3115', 'KP 022014',
       '3-59-0951', '010/0058/Sidamo', 'HDOA 210310', '3-37-1829',
       '37/672/0016', '002/1251/0242', '016-2484-04', 'HDOA#210306',
       '11-194-0014', '3-37-0277', '3-37-4824', 'C47', '3-37-0416',
       '1104385872', '002/1251/0070', '002/1251/0066', '37/00395/0335',
       '220457', 'KE 9143', '13-63-174', '9-29-1986', '1-053-0222',
       '09-392-69', '5-423-0128', '11/08/0109', '5-114-0171', '33',
       '58180422', '5-0048-0052', '5-1106-0011', '3-79-0543',
       '11/23/1088', '11/1886/02', '703816889, 108282,703816891',
       '3-37-1724', '3-37-1291', 'KE 3127', '11/972/26', '11-23-0291',
       '3-79-0542', '3-37-0930', '3-68-0224', '3-68-0005',
       '002/1251/0069', '002/1251/0076', '5-0015-0029',
       '035/170/5071146\u2060\u2060\u2060\u2060', '5-114-0170', '01-4008',
       '1', '11/23/0398', '1104548679', '2222', '11/326/06', 'mmm',
       'TEST', '5-0015-0231', 'To be advice', '3-59-0318', '3-37-2940',
       '2234501 KONA FANCY', '1506545936', '13-111-023', '03-05-0845',
       '13-111-032', '3-37-1704', '3-59-2235', '3-68-0225', '1506680144',
       '002/1251/0360', '11-897-10', '3-59-3461', '11/11711/59',
       '11/52/709', '3-37-0637', '3-37-4823', '01-3576', '3-59-2270',
       'C46', 'C12', '11/23/0561', '3-68-0290', '2230302 KONA NO. 1',
       '11/23/0365', '3-37-3825', '5-818-0450', '11/52/1170', '11/752/01',
       '11/23/0335', '3-37-4173', '017/176/165', '002/1495/0607',
       '5-025-0111', 'C31', '329', '11/43984/0001', '37-0569-2730',
       'not assigned', '11/9772/2', '09-060-24', '3-68-0019',
       '11-853-053', '3-59-0503', '11/23/0178', '3-37-0118', '-',
       '2234504 KONA PRIME', '1405843946', '010-0343-0083', '13-111-038',
       '11/52/841', '613', '11/23/0535', '11/23/0465', '1032',
       '14-3-79-1417', '3-37-2301', '002/4177/0121', '68-0222',
       '37-0569-2347', '002/1660/0079', '016-1273-101', '002/1660/0105',
       '3-59-1772', '3-37', 'none', '03-01-5274', '01-1969', '3-37-0985',
       'Taiwan台灣', '3-79-0635', '1207088353', '2671', '3-59-2888',
       '3-37-2112', '5-025-0249', '11/11711/60', '002/4177/0150',
       '002/1660/0066', '5-0048-0145', '11/23/0436', '3-68-0221',
       '11/23/0464', '1302922721', '222', '002/1352/0052',
       'Thailand/Organic/FT/FLO 19467/2011-A/140', '37-0985-4132',
       '3-59-0075', '3-37-1510', '3-59-0708', '3-37-1419', '3-259-0471',
       '3-68-0049', '3-68-0260', 'K#13150104', '11-10170-005',
       '3-059-1329', '3-68-0124', 'HDOA 210689', '002/1660/0080',
       '37-0985-4045', '13 / 111 / 053', '017/001/1412', '002/1660/0106',
       '5-025-0109', '3-259-1444', '11-52-380', '3-68-0021', '3-37-2865',
       '11/23/0634', '11/23/0420', '3-68-0045', '11-183-22', '11/23/0933',
       '1207033381', '11/11711/08', 'HDOA 210345', '3-37-2548',
       '3-37-0636', '016-2028-042', '14-3-79-1921', '14-3-79-0953',
       '3-79-0828', '3-37-1824', '002/1251/0181', '3-59-1695',
       '5-025-0250', '3-59-1919', '11/23/0145', '3-37-0634', 'CA007',
       '01-1437', '3-68-0068', '11-023-0025', '3-79-2009', '13-111-240',
       '3-68-0161', '3-68-0183', '01-04', '2484', '11/752/02',
       '3-37-0666', '11/23/0237', 'HDOA #210308', '015-282', '3-59-0504',
       '11/23/0696', '3-59-2318', '5-025-0032', '7697', '9-391-73',
       '3-59-2236', '002/4542/0886', 'C50', '15-3-79-0002', '11/23/0562',
       '11/11711/6', '11/23/1040', '2233803 KONA NO. 1', '3-68-0147',
       '03-01-0424', 'HDOA 210127 Kona Extra Fancy',
       '016-2729-001-A-LAB-SS2', '68-0054', '3-37-3729', '3-37-2623',
       '1620280402', '3-68-0103', 'C27', '5-562-0013', 'KP012314',
       '5-0048-0023', '030-0695-1742', '3-59-1326', '11/23/0419',
       '2234503 KONA PRIME', '3-68-0133', 'HDOA #210307', '5-139-0050',
       '11/973/152', '035/170/5061178', '002/4542/0189', '3', 'Taiwanw台灣',
       '3-79-1818', '11-11711-85 (MED)', '2406', 'KF313630', '11/23/0767',
       '002/1251/0241', '3-68-0089', '3-37-0661', '3-68-0205',
       '3-68-0107', '3-068-0108', '11/23/0673', '033/0004', '543',
       '11/11711/58', '13-63-214', '9-392-68', '11/11711/1', '11/23/2004',
       '37-0843-3305', 'C9', '3-37-0119', 'unkown', '13-01-2369',
       '13-111-193', '11-326-10', 'KS011714', '4', '016-2129',
       '1702765464', '1702771046', '3-37-1691', '1702766681', '3-68-0140',
       '002/1251/0250', '002/1251/0245', '11-26-0236', '002/1251/0075',
       '9-29-1990', '010/0182/0008', '3-59-1694', '3-37-0278',
       '002/1660/0049', '002/4177/0164', '002/4542/0477', '002/1660/0064',
       '05-0048-0171', 'KP011714', 'K131353', '1405830166', '220454',
       '2135403', '3-37-2781', '3-68-0129', '11/851/0022', 'C201501',
       'C201502', '3-59-1773', '11-973-94', '11/326/19', '11/11711/38',
       '651', '11-11711-86 (SV)', '5-0048-0022', '002/1352/0077',
       '3-37-0281', '3-68-0248', '3-59-1150', '3-59-1327', '3-37-0021',
       '1104362909', '1302911347', '3-68-0141', '11/194/07', '3-37-0170',
       'HDOA #210391', 'HDOA #210363', '09-030-273', '3-37-4468',
       '010/0357/0085', '123', '444', '16', '999', '11-11711-27',
       '11-11711-84 (S.V.S.A)', '11-049-0093', '3-37-2864', '3-68-0145',
       '3-259.0267', '1489', '2200301', '3-37-2759', '11/23/0513',
       '002/1660/0047', '09-0488-1', '11/23/0578', '002/1495/0695',
       '3015388', '015/1691/065', '3-320-0025', '3-37-1765',
       '033/DE/006/007', '2676', '1104373099', '11/23/0934', '9-29-1991',
       '11-43367-27', '11-973-276', '11/23/0693', '11/23/0632',
       '11/23/0690', '11/23/0369', '09-134-17', '002/1660/0048',
       '5300343627999', '3-37-0127', 'C21', '11/972/34', '3-201-1817',
       'KP010914', 'KF010914', '3-332-0028', '1104289425', '1302910536',
       '3-79-0334', '3-37-0767', '2135401', '29', 'HDOA 210688',
       '09-0488-001', '3- 01-6894', '002/4542/0213', 'C25', 'C20',
       '703805790', '793', '009/0060/44L1', '1506622904', 'F-30002939',
       '2889', '016-2484-05', '3-68-0152', '3-037-2273', '002/4542/0190',
       '015/0826/0516', 'Thailand', 'C37', '5-0048-0125', '016-2022-0008',
       '2', '3-68-0160', '3-68-0004', '1405818311',
       '703815218; 703815215; 703815197', '3-37-1435', '002/1251/0359',
       '13-111-097', '11/23/0146', 'C26', 'C35', '002 - 4177 - 0039',
       '11/23/0633', '3-68-0162', '11/426/2', '1702773555', '1206966823',
       'PCO-031106-CF7', '11/08/88-11/08/67', '002/1352/0099',
       '3-37-0582', '2135402', '11/0052/0538', '11/23/0639', '11/23/0366',
       '11/23/0400', '11/43367/12', '3-37-4434', 'GOP', '11-023-0024',
       '002/1251/0228', '030-0595-0128', '3-37-2044', '3252',
       '1104558673', '120706171, 1207106169', '125464', '3-59-0782',
       '002/1251/185', '3-68-0066', '3-68-0262', '13-111-022',
       '02 / 143-0 / 0044', '5-025-0294', '5/423/0127', '002/1660/0107',
       '002/4542/0478', '11-52-349', 'C22', '002/1660/0065', '11/972/28',
       '016-2022-0010', '3-037-996', '11/23/1015', '68-0220',
       '11/9768/02', '1702806437', '11/23/0394', '002/1251/0243',
       '002/1251/0247', '3-59-0787', '002/1566/0003', '11/973/158', '391',
       '13-63-206', '1104387103', 'KF3150140', '842046', '11-11711-19',
       '009/0060/45L2', '1102751473', '3-68-0088', '3-37-0663',
       '002/1251/0183', '3-37-1979', '13-111-054', '16042', 'CA058',
       '3881832/P1412427', '49881', '11873168', '002/4542/0274', 'C33',
       '3-68-0144', '1702764973', '11/00183/00020', '3196666',
       '70381402, 70381402, 703815394', '3-68-0154', '03-05-0846',
       '5-019-0060', 'C19', '3-59-1656', '5-025-0101', '230035',
       '1104362837', '1102751467', '2200302', '13-111-024', 'CA006',
       '105', 'C42', 'C120', '10704180', '5-0048-0144', '13-123-306',
       '3-37-2863', '??', '1104355254', '002/1251/0237', '002/1251/0240',
       '11/08/1990', '001/1251/0253', '11/23/0238', '3-37-2782',
       '11/23/0515', '09-032-86', '11-973-59', 'C13', '17/176/0125B',
       '13-137-004', '1700920709', '1702772190', '1104402366',
       '002/1241/0244', '3-068-141', '02/0143-0/0292', '015/1969/008',
       '11/23/0507', 'unspecified', '13-63-301', '5-019-0118', '15041753',
       '13-111-311', '0016-2814-0002', '3-37-2547', 'KF315210',
       '002/1352/0159', '11/23/0397', '1506543018', '1104363377',
       '002/1251/0361', '3-68-0206', 'HDOA 210281', '11/23/0514', 'C15',
       '2-1495-529', '1702772155', '1104372561',
       '2037240, 2037150,1400213685', '3-68-0059', '3-37-2930',
       '11/23/0640', '11/23/0701', '033/0004/0191', '017/001/534', 'C001',
       'C39', '002/4177/0161', '15/1595/0021', '13-111-192', '5-025-0135',
       '016-2022-0009', '2496', '11/9768/01', '1506803385', '2200305',
       '11/23/0368', '5-025-024/25', 'C30', '002/1660/0058', '11/23/1014',
       'Thailand/Organic/FT/Peaberry/Crop 2011P', '11/23/0688',
       '017-053-0211 / 017-053-0212', '13-111-083', '11/23/0367',
       '5-545-0006', 'C18', '11/951/388', '002/135-2/0276', '1506811628',
       '1506546082', '1302919531', 'na', '11/23/0239', '11/326/14',
       '002/1495/0134', '13-63-204', '0016-2814-0001', '030-0218-2662',
       '11/9772/3', '1702771645', 'F30002939', '3-68-0027', '3-68-0130',
       'HDOA 210520', '3-37-0059', '13-111-084', '13-63-318',
       '002/135-2/0076', '123/300/01', '13-01-0556',
       '002/1566/0003        ', '017/001/1214', 'C38', '1507169991',
       '017-053-0134', 'A057', '13-111-037', 'C16', '5-0048-0126',
       '002/454-2/0379', '11-183-25', '002/1251/0182', '010/0475/0522',
       '017/001/652', 'C006', '5-545-0005', '1405833052, 1405833062',
       '1955', '2200304', '002/4542/0044', '002/4542/0966', '11/23/0506',
       '3-37-4378', '11/23/0706', '13-132-92', '002/4542/0275', 'C23',
       '10589010', '1506558878', '11/23/0689', 'KP121714', 'C002',
       '002/135-2/0075', '17/009/0057', '11/972/29', '1104386282',
       '11-873-054', '1506717737', '1201255296', '2200303', '3-068-0123',
       '002/4542/0021', 'Unspecified', '017/001/1066', '13-111-035',
       '5-562-0014', '1401325570, 1405822583, 1405822338', 'None exists',
       '2131202', 'non', '015/1691/006', '5-025-0048', 'C17',
       '14-3-79-1034', '11/23/0233', '11/23/0240', '3-37-1980',
       '017-053-0046', 'C28', '13-123-238', '11-52-121', 'HDOA 210282',
       '11/15/0293', '13-154-234', 'not applicable', '002/4542/0049',
       '11-951-136', '002/135-2/0182', '11/52/492', '1405793051',
       '13-63-60', 'CNY', '1405675414', '027/01/601', 'A053',
       '11/23/0795', '2135405', '010/0058', '002/143-0/0058',
       '017/117/018', 'KPP021114', '11-23-1972', '1702801679',
       '017-053-0125', '13-63-70', '11/23/1170', '1104362940',
       '1405791535', '1104367469', '11/23/0582', '002/1352/0226', '17',
       '1401045726', '017/001/1638', '0016-2050-0001', '03-01-2700',
       'KP022414', '1506729960', '017/191/488', '1104276076',
       'HDOA 220468 Kona Prime', '10703510', '030-0595-0508', '5-066-038',
       '1405811686', 'FINCA MEDINA 11/11711/01-LOGO APCA', '1506622214',
       '11/23/0508', '9', '11/23/0957', '1702807163', '1104363350',
       '1104379888', '3-68-0153', '11-194-0008', '017/176/160', '68-0197',
       '145092', '11/23/0358', '3-279-390', '1104340088', '1104275271',
       '11/23/0122', '11/23/0168', '2728', '016/2362/0057', '1405792893',
       '1207093598', '11-951-388', '13-117-87', '030-0582-0050',
       '2074632', 'F07016865', '017-053-0211/053-0212',
       'Specialty Coffee Association of America', '11/23/1020',
       '11042707999', 'LOUIS88', '1104374276', '017-053', '1506502938',
       '703817078, 703817042, 700137443', 'HDOA 210542', '0016-2795-0008',
       '1506868415', 'K#1 21614', '11/23/0334', '11/23/0101', 'KP120314',
       '2209401 KONA PRIME', '1104341113', '13-117-88', 'KF 21614',
       '1506558883', '03/01/1632', '5-545-0007', '11/23/0121', '16039',
       '11/23/0333', 'KP3150140', '110548082', '11/426/1', '1506558882',
       '30', '14/7/2015/172', '016/2362/0051', '11/23/01', 'KPBP 21114',
       'Specialty Coffee Association', '1405792248', '1104372556',
       '11/23/0768', '2670', 'F07008657', 'KPBP 022414', '11/23/0796',
       '1104820070', '220456', '0016-2722-0001', '5-545-0015', '11111',
       '1104351023', '0016-2847-0001', '1104328663',
       '017-053-0211/ 017-053-0212', '11/853/165', '14/1148/2017/21',
       '0000', '14/1148/2017/18', '14/1148/2016/17', '14/1148/2016/12',
       '14-1118-2014-0087'], dtype=object)

In [49]:
# There are NaN values so I replace them with "Unknown"
coffee_data["ico_number"] = coffee_data["ico_number"].fillna("Unknown")

In [50]:
coffee_data["ico_number"].unique()

array(['2014/2015', 'Unknown', '010/0338', '2014/15', 'unknown',
       '010/0056', '100181006', '5-562-0015', '0', '002/1251/0073',
       '010/0056/Sidamo', '13-111-053', 'Taiwan', '790-0013', 'A019116',
       '002/1251/0068', '5818009', '220452', 'HDOA 210128 Kona Fancy',
       '010/0170', '01-011-512', '002/1352/0045', 'NIL', '002/1251/0071',
       'NONE', 'x', '010/0145', '11/23/0252', '3-68-0215', '11/1886/03',
       '11-853-155', '490', '030-0537-2066', '25072012', '09 – 060-24',
       '220451', '290503', '3707361715', '2015', '11-52-492', '220453',
       '002/1251/0072', '9-060-60D-L-1D', '11999144', '5-562-0006',
       '5-562-0016', '37/672/0017', '37/00597/0252 - AB FAQ Q certified',
       '010/0157', '010/0001/0022', '11/23/0177', '3-68-0102',
       '3-79-0634', '11-30-0593', '495', '3-59-3115', 'KP 022014',
       '3-59-0951', '010/0058/Sidamo', 'HDOA 210310', '3-37-1829',
       '37/672/0016', '002/1251/0242', '016-2484-04', 'HDOA#210306',
       '11-194-0014', '3-37-0277', '3-37-4824', 'C47', '3-37-0416',
       '1104385872', '002/1251/0070', '002/1251/0066', '37/00395/0335',
       '220457', 'KE 9143', '13-63-174', '9-29-1986', '1-053-0222',
       '09-392-69', '5-423-0128', '11/08/0109', '5-114-0171', '33',
       '58180422', '5-0048-0052', '5-1106-0011', '3-79-0543',
       '11/23/1088', '11/1886/02', '703816889, 108282,703816891',
       '3-37-1724', '3-37-1291', 'KE 3127', '11/972/26', '11-23-0291',
       '3-79-0542', '3-37-0930', '3-68-0224', '3-68-0005',
       '002/1251/0069', '002/1251/0076', '5-0015-0029',
       '035/170/5071146\u2060\u2060\u2060\u2060', '5-114-0170', '01-4008',
       '1', '11/23/0398', '1104548679', '2222', '11/326/06', 'mmm',
       'TEST', '5-0015-0231', 'To be advice', '3-59-0318', '3-37-2940',
       '2234501 KONA FANCY', '1506545936', '13-111-023', '03-05-0845',
       '13-111-032', '3-37-1704', '3-59-2235', '3-68-0225', '1506680144',
       '002/1251/0360', '11-897-10', '3-59-3461', '11/11711/59',
       '11/52/709', '3-37-0637', '3-37-4823', '01-3576', '3-59-2270',
       'C46', 'C12', '11/23/0561', '3-68-0290', '2230302 KONA NO. 1',
       '11/23/0365', '3-37-3825', '5-818-0450', '11/52/1170', '11/752/01',
       '11/23/0335', '3-37-4173', '017/176/165', '002/1495/0607',
       '5-025-0111', 'C31', '329', '11/43984/0001', '37-0569-2730',
       'not assigned', '11/9772/2', '09-060-24', '3-68-0019',
       '11-853-053', '3-59-0503', '11/23/0178', '3-37-0118', '-',
       '2234504 KONA PRIME', '1405843946', '010-0343-0083', '13-111-038',
       '11/52/841', '613', '11/23/0535', '11/23/0465', '1032',
       '14-3-79-1417', '3-37-2301', '002/4177/0121', '68-0222',
       '37-0569-2347', '002/1660/0079', '016-1273-101', '002/1660/0105',
       '3-59-1772', '3-37', 'none', '03-01-5274', '01-1969', '3-37-0985',
       'Taiwan台灣', '3-79-0635', '1207088353', '2671', '3-59-2888',
       '3-37-2112', '5-025-0249', '11/11711/60', '002/4177/0150',
       '002/1660/0066', '5-0048-0145', '11/23/0436', '3-68-0221',
       '11/23/0464', '1302922721', '222', '002/1352/0052',
       'Thailand/Organic/FT/FLO 19467/2011-A/140', '37-0985-4132',
       '3-59-0075', '3-37-1510', '3-59-0708', '3-37-1419', '3-259-0471',
       '3-68-0049', '3-68-0260', 'K#13150104', '11-10170-005',
       '3-059-1329', '3-68-0124', 'HDOA 210689', '002/1660/0080',
       '37-0985-4045', '13 / 111 / 053', '017/001/1412', '002/1660/0106',
       '5-025-0109', '3-259-1444', '11-52-380', '3-68-0021', '3-37-2865',
       '11/23/0634', '11/23/0420', '3-68-0045', '11-183-22', '11/23/0933',
       '1207033381', '11/11711/08', 'HDOA 210345', '3-37-2548',
       '3-37-0636', '016-2028-042', '14-3-79-1921', '14-3-79-0953',
       '3-79-0828', '3-37-1824', '002/1251/0181', '3-59-1695',
       '5-025-0250', '3-59-1919', '11/23/0145', '3-37-0634', 'CA007',
       '01-1437', '3-68-0068', '11-023-0025', '3-79-2009', '13-111-240',
       '3-68-0161', '3-68-0183', '01-04', '2484', '11/752/02',
       '3-37-0666', '11/23/0237', 'HDOA #210308', '015-282', '3-59-0504',
       '11/23/0696', '3-59-2318', '5-025-0032', '7697', '9-391-73',
       '3-59-2236', '002/4542/0886', 'C50', '15-3-79-0002', '11/23/0562',
       '11/11711/6', '11/23/1040', '2233803 KONA NO. 1', '3-68-0147',
       '03-01-0424', 'HDOA 210127 Kona Extra Fancy',
       '016-2729-001-A-LAB-SS2', '68-0054', '3-37-3729', '3-37-2623',
       '1620280402', '3-68-0103', 'C27', '5-562-0013', 'KP012314',
       '5-0048-0023', '030-0695-1742', '3-59-1326', '11/23/0419',
       '2234503 KONA PRIME', '3-68-0133', 'HDOA #210307', '5-139-0050',
       '11/973/152', '035/170/5061178', '002/4542/0189', '3', 'Taiwanw台灣',
       '3-79-1818', '11-11711-85 (MED)', '2406', 'KF313630', '11/23/0767',
       '002/1251/0241', '3-68-0089', '3-37-0661', '3-68-0205',
       '3-68-0107', '3-068-0108', '11/23/0673', '033/0004', '543',
       '11/11711/58', '13-63-214', '9-392-68', '11/11711/1', '11/23/2004',
       '37-0843-3305', 'C9', '3-37-0119', 'unkown', '13-01-2369',
       '13-111-193', '11-326-10', 'KS011714', '4', '016-2129',
       '1702765464', '1702771046', '3-37-1691', '1702766681', '3-68-0140',
       '002/1251/0250', '002/1251/0245', '11-26-0236', '002/1251/0075',
       '9-29-1990', '010/0182/0008', '3-59-1694', '3-37-0278',
       '002/1660/0049', '002/4177/0164', '002/4542/0477', '002/1660/0064',
       '05-0048-0171', 'KP011714', 'K131353', '1405830166', '220454',
       '2135403', '3-37-2781', '3-68-0129', '11/851/0022', 'C201501',
       'C201502', '3-59-1773', '11-973-94', '11/326/19', '11/11711/38',
       '651', '11-11711-86 (SV)', '5-0048-0022', '002/1352/0077',
       '3-37-0281', '3-68-0248', '3-59-1150', '3-59-1327', '3-37-0021',
       '1104362909', '1302911347', '3-68-0141', '11/194/07', '3-37-0170',
       'HDOA #210391', 'HDOA #210363', '09-030-273', '3-37-4468',
       '010/0357/0085', '123', '444', '16', '999', '11-11711-27',
       '11-11711-84 (S.V.S.A)', '11-049-0093', '3-37-2864', '3-68-0145',
       '3-259.0267', '1489', '2200301', '3-37-2759', '11/23/0513',
       '002/1660/0047', '09-0488-1', '11/23/0578', '002/1495/0695',
       '3015388', '015/1691/065', '3-320-0025', '3-37-1765',
       '033/DE/006/007', '2676', '1104373099', '11/23/0934', '9-29-1991',
       '11-43367-27', '11-973-276', '11/23/0693', '11/23/0632',
       '11/23/0690', '11/23/0369', '09-134-17', '002/1660/0048',
       '5300343627999', '3-37-0127', 'C21', '11/972/34', '3-201-1817',
       'KP010914', 'KF010914', '3-332-0028', '1104289425', '1302910536',
       '3-79-0334', '3-37-0767', '2135401', '29', 'HDOA 210688',
       '09-0488-001', '3- 01-6894', '002/4542/0213', 'C25', 'C20',
       '703805790', '793', '009/0060/44L1', '1506622904', 'F-30002939',
       '2889', '016-2484-05', '3-68-0152', '3-037-2273', '002/4542/0190',
       '015/0826/0516', 'Thailand', 'C37', '5-0048-0125', '016-2022-0008',
       '2', '3-68-0160', '3-68-0004', '1405818311',
       '703815218; 703815215; 703815197', '3-37-1435', '002/1251/0359',
       '13-111-097', '11/23/0146', 'C26', 'C35', '002 - 4177 - 0039',
       '11/23/0633', '3-68-0162', '11/426/2', '1702773555', '1206966823',
       'PCO-031106-CF7', '11/08/88-11/08/67', '002/1352/0099',
       '3-37-0582', '2135402', '11/0052/0538', '11/23/0639', '11/23/0366',
       '11/23/0400', '11/43367/12', '3-37-4434', 'GOP', '11-023-0024',
       '002/1251/0228', '030-0595-0128', '3-37-2044', '3252',
       '1104558673', '120706171, 1207106169', '125464', '3-59-0782',
       '002/1251/185', '3-68-0066', '3-68-0262', '13-111-022',
       '02 / 143-0 / 0044', '5-025-0294', '5/423/0127', '002/1660/0107',
       '002/4542/0478', '11-52-349', 'C22', '002/1660/0065', '11/972/28',
       '016-2022-0010', '3-037-996', '11/23/1015', '68-0220',
       '11/9768/02', '1702806437', '11/23/0394', '002/1251/0243',
       '002/1251/0247', '3-59-0787', '002/1566/0003', '11/973/158', '391',
       '13-63-206', '1104387103', 'KF3150140', '842046', '11-11711-19',
       '009/0060/45L2', '1102751473', '3-68-0088', '3-37-0663',
       '002/1251/0183', '3-37-1979', '13-111-054', '16042', 'CA058',
       '3881832/P1412427', '49881', '11873168', '002/4542/0274', 'C33',
       '3-68-0144', '1702764973', '11/00183/00020', '3196666',
       '70381402, 70381402, 703815394', '3-68-0154', '03-05-0846',
       '5-019-0060', 'C19', '3-59-1656', '5-025-0101', '230035',
       '1104362837', '1102751467', '2200302', '13-111-024', 'CA006',
       '105', 'C42', 'C120', '10704180', '5-0048-0144', '13-123-306',
       '3-37-2863', '??', '1104355254', '002/1251/0237', '002/1251/0240',
       '11/08/1990', '001/1251/0253', '11/23/0238', '3-37-2782',
       '11/23/0515', '09-032-86', '11-973-59', 'C13', '17/176/0125B',
       '13-137-004', '1700920709', '1702772190', '1104402366',
       '002/1241/0244', '3-068-141', '02/0143-0/0292', '015/1969/008',
       '11/23/0507', 'unspecified', '13-63-301', '5-019-0118', '15041753',
       '13-111-311', '0016-2814-0002', '3-37-2547', 'KF315210',
       '002/1352/0159', '11/23/0397', '1506543018', '1104363377',
       '002/1251/0361', '3-68-0206', 'HDOA 210281', '11/23/0514', 'C15',
       '2-1495-529', '1702772155', '1104372561',
       '2037240, 2037150,1400213685', '3-68-0059', '3-37-2930',
       '11/23/0640', '11/23/0701', '033/0004/0191', '017/001/534', 'C001',
       'C39', '002/4177/0161', '15/1595/0021', '13-111-192', '5-025-0135',
       '016-2022-0009', '2496', '11/9768/01', '1506803385', '2200305',
       '11/23/0368', '5-025-024/25', 'C30', '002/1660/0058', '11/23/1014',
       'Thailand/Organic/FT/Peaberry/Crop 2011P', '11/23/0688',
       '017-053-0211 / 017-053-0212', '13-111-083', '11/23/0367',
       '5-545-0006', 'C18', '11/951/388', '002/135-2/0276', '1506811628',
       '1506546082', '1302919531', 'na', '11/23/0239', '11/326/14',
       '002/1495/0134', '13-63-204', '0016-2814-0001', '030-0218-2662',
       '11/9772/3', '1702771645', 'F30002939', '3-68-0027', '3-68-0130',
       'HDOA 210520', '3-37-0059', '13-111-084', '13-63-318',
       '002/135-2/0076', '123/300/01', '13-01-0556',
       '002/1566/0003        ', '017/001/1214', 'C38', '1507169991',
       '017-053-0134', 'A057', '13-111-037', 'C16', '5-0048-0126',
       '002/454-2/0379', '11-183-25', '002/1251/0182', '010/0475/0522',
       '017/001/652', 'C006', '5-545-0005', '1405833052, 1405833062',
       '1955', '2200304', '002/4542/0044', '002/4542/0966', '11/23/0506',
       '3-37-4378', '11/23/0706', '13-132-92', '002/4542/0275', 'C23',
       '10589010', '1506558878', '11/23/0689', 'KP121714', 'C002',
       '002/135-2/0075', '17/009/0057', '11/972/29', '1104386282',
       '11-873-054', '1506717737', '1201255296', '2200303', '3-068-0123',
       '002/4542/0021', 'Unspecified', '017/001/1066', '13-111-035',
       '5-562-0014', '1401325570, 1405822583, 1405822338', 'None exists',
       '2131202', 'non', '015/1691/006', '5-025-0048', 'C17',
       '14-3-79-1034', '11/23/0233', '11/23/0240', '3-37-1980',
       '017-053-0046', 'C28', '13-123-238', '11-52-121', 'HDOA 210282',
       '11/15/0293', '13-154-234', 'not applicable', '002/4542/0049',
       '11-951-136', '002/135-2/0182', '11/52/492', '1405793051',
       '13-63-60', 'CNY', '1405675414', '027/01/601', 'A053',
       '11/23/0795', '2135405', '010/0058', '002/143-0/0058',
       '017/117/018', 'KPP021114', '11-23-1972', '1702801679',
       '017-053-0125', '13-63-70', '11/23/1170', '1104362940',
       '1405791535', '1104367469', '11/23/0582', '002/1352/0226', '17',
       '1401045726', '017/001/1638', '0016-2050-0001', '03-01-2700',
       'KP022414', '1506729960', '017/191/488', '1104276076',
       'HDOA 220468 Kona Prime', '10703510', '030-0595-0508', '5-066-038',
       '1405811686', 'FINCA MEDINA 11/11711/01-LOGO APCA', '1506622214',
       '11/23/0508', '9', '11/23/0957', '1702807163', '1104363350',
       '1104379888', '3-68-0153', '11-194-0008', '017/176/160', '68-0197',
       '145092', '11/23/0358', '3-279-390', '1104340088', '1104275271',
       '11/23/0122', '11/23/0168', '2728', '016/2362/0057', '1405792893',
       '1207093598', '11-951-388', '13-117-87', '030-0582-0050',
       '2074632', 'F07016865', '017-053-0211/053-0212',
       'Specialty Coffee Association of America', '11/23/1020',
       '11042707999', 'LOUIS88', '1104374276', '017-053', '1506502938',
       '703817078, 703817042, 700137443', 'HDOA 210542', '0016-2795-0008',
       '1506868415', 'K#1 21614', '11/23/0334', '11/23/0101', 'KP120314',
       '2209401 KONA PRIME', '1104341113', '13-117-88', 'KF 21614',
       '1506558883', '03/01/1632', '5-545-0007', '11/23/0121', '16039',
       '11/23/0333', 'KP3150140', '110548082', '11/426/1', '1506558882',
       '30', '14/7/2015/172', '016/2362/0051', '11/23/01', 'KPBP 21114',
       'Specialty Coffee Association', '1405792248', '1104372556',
       '11/23/0768', '2670', 'F07008657', 'KPBP 022414', '11/23/0796',
       '1104820070', '220456', '0016-2722-0001', '5-545-0015', '11111',
       '1104351023', '0016-2847-0001', '1104328663',
       '017-053-0211/ 017-053-0212', '11/853/165', '14/1148/2017/21',
       '0000', '14/1148/2017/18', '14/1148/2016/17', '14/1148/2016/12',
       '14-1118-2014-0087'], dtype=object)

In [51]:
# Replace all symbols such as '-' with '/' as this is the correct format
import re
coffee_data['ico_number'] = coffee_data['ico_number'].str.replace(r'(?<=\d)[^\d]+(?=\d)', '/', regex=True)

In [52]:
coffee_data['ico_number'].unique()

array(['2014/2015', 'Unknown', '010/0338', '2014/15', 'unknown',
       '010/0056', '100181006', '5/562/0015', '0', '002/1251/0073',
       '010/0056/Sidamo', '13/111/053', 'Taiwan', '790/0013', 'A019116',
       '002/1251/0068', '5818009', '220452', 'HDOA 210128 Kona Fancy',
       '010/0170', '01/011/512', '002/1352/0045', 'NIL', '002/1251/0071',
       'NONE', 'x', '010/0145', '11/23/0252', '3/68/0215', '11/1886/03',
       '11/853/155', '490', '030/0537/2066', '25072012', '09/060/24',
       '220451', '290503', '3707361715', '2015', '11/52/492', '220453',
       '002/1251/0072', '9/060/60/1D', '11999144', '5/562/0006',
       '5/562/0016', '37/672/0017', '37/00597/0252 - AB FAQ Q certified',
       '010/0157', '010/0001/0022', '11/23/0177', '3/68/0102',
       '3/79/0634', '11/30/0593', '495', '3/59/3115', 'KP 022014',
       '3/59/0951', '010/0058/Sidamo', 'HDOA 210310', '3/37/1829',
       '37/672/0016', '002/1251/0242', '016/2484/04', 'HDOA#210306',
       '11/194/0014', '3/37/0277', '3/37/4824', 'C47', '3/37/0416',
       '1104385872', '002/1251/0070', '002/1251/0066', '37/00395/0335',
       '220457', 'KE 9143', '13/63/174', '9/29/1986', '1/053/0222',
       '09/392/69', '5/423/0128', '11/08/0109', '5/114/0171', '33',
       '58180422', '5/0048/0052', '5/1106/0011', '3/79/0543',
       '11/23/1088', '11/1886/02', '703816889/108282/703816891',
       '3/37/1724', '3/37/1291', 'KE 3127', '11/972/26', '11/23/0291',
       '3/79/0542', '3/37/0930', '3/68/0224', '3/68/0005',
       '002/1251/0069', '002/1251/0076', '5/0015/0029',
       '035/170/5071146\u2060\u2060\u2060\u2060', '5/114/0170', '01/4008',
       '1', '11/23/0398', '1104548679', '2222', '11/326/06', 'mmm',
       'TEST', '5/0015/0231', 'To be advice', '3/59/0318', '3/37/2940',
       '2234501 KONA FANCY', '1506545936', '13/111/023', '03/05/0845',
       '13/111/032', '3/37/1704', '3/59/2235', '3/68/0225', '1506680144',
       '002/1251/0360', '11/897/10', '3/59/3461', '11/11711/59',
       '11/52/709', '3/37/0637', '3/37/4823', '01/3576', '3/59/2270',
       'C46', 'C12', '11/23/0561', '3/68/0290', '2230302/1', '11/23/0365',
       '3/37/3825', '5/818/0450', '11/52/1170', '11/752/01', '11/23/0335',
       '3/37/4173', '017/176/165', '002/1495/0607', '5/025/0111', 'C31',
       '329', '11/43984/0001', '37/0569/2730', 'not assigned',
       '11/9772/2', '3/68/0019', '11/853/053', '3/59/0503', '11/23/0178',
       '3/37/0118', '-', '2234504 KONA PRIME', '1405843946',
       '010/0343/0083', '13/111/038', '11/52/841', '613', '11/23/0535',
       '11/23/0465', '1032', '14/3/79/1417', '3/37/2301', '002/4177/0121',
       '68/0222', '37/0569/2347', '002/1660/0079', '016/1273/101',
       '002/1660/0105', '3/59/1772', '3/37', 'none', '03/01/5274',
       '01/1969', '3/37/0985', 'Taiwan台灣', '3/79/0635', '1207088353',
       '2671', '3/59/2888', '3/37/2112', '5/025/0249', '11/11711/60',
       '002/4177/0150', '002/1660/0066', '5/0048/0145', '11/23/0436',
       '3/68/0221', '11/23/0464', '1302922721', '222', '002/1352/0052',
       'Thailand/Organic/FT/FLO 19467/2011/140', '37/0985/4132',
       '3/59/0075', '3/37/1510', '3/59/0708', '3/37/1419', '3/259/0471',
       '3/68/0049', '3/68/0260', 'K#13150104', '11/10170/005',
       '3/059/1329', '3/68/0124', 'HDOA 210689', '002/1660/0080',
       '37/0985/4045', '017/001/1412', '002/1660/0106', '5/025/0109',
       '3/259/1444', '11/52/380', '3/68/0021', '3/37/2865', '11/23/0634',
       '11/23/0420', '3/68/0045', '11/183/22', '11/23/0933', '1207033381',
       '11/11711/08', 'HDOA 210345', '3/37/2548', '3/37/0636',
       '016/2028/042', '14/3/79/1921', '14/3/79/0953', '3/79/0828',
       '3/37/1824', '002/1251/0181', '3/59/1695', '5/025/0250',
       '3/59/1919', '11/23/0145', '3/37/0634', 'CA007', '01/1437',
       '3/68/0068', '11/023/0025', '3/79/2009', '13/111/240', '3/68/0161',
       '3/68/0183', '01/04', '2484', '11/752/02', '3/37/0666',
       '11/23/0237', 'HDOA #210308', '015/282', '3/59/0504', '11/23/0696',
       '3/59/2318', '5/025/0032', '7697', '9/391/73', '3/59/2236',
       '002/4542/0886', 'C50', '15/3/79/0002', '11/23/0562', '11/11711/6',
       '11/23/1040', '2233803/1', '3/68/0147', '03/01/0424',
       'HDOA 210127 Kona Extra Fancy', '016/2729/001/2', '68/0054',
       '3/37/3729', '3/37/2623', '1620280402', '3/68/0103', 'C27',
       '5/562/0013', 'KP012314', '5/0048/0023', '030/0695/1742',
       '3/59/1326', '11/23/0419', '2234503 KONA PRIME', '3/68/0133',
       'HDOA #210307', '5/139/0050', '11/973/152', '035/170/5061178',
       '002/4542/0189', '3', 'Taiwanw台灣', '3/79/1818',
       '11/11711/85 (MED)', '2406', 'KF313630', '11/23/0767',
       '002/1251/0241', '3/68/0089', '3/37/0661', '3/68/0205',
       '3/68/0107', '3/068/0108', '11/23/0673', '033/0004', '543',
       '11/11711/58', '13/63/214', '9/392/68', '11/11711/1', '11/23/2004',
       '37/0843/3305', 'C9', '3/37/0119', 'unkown', '13/01/2369',
       '13/111/193', '11/326/10', 'KS011714', '4', '016/2129',
       '1702765464', '1702771046', '3/37/1691', '1702766681', '3/68/0140',
       '002/1251/0250', '002/1251/0245', '11/26/0236', '002/1251/0075',
       '9/29/1990', '010/0182/0008', '3/59/1694', '3/37/0278',
       '002/1660/0049', '002/4177/0164', '002/4542/0477', '002/1660/0064',
       '05/0048/0171', 'KP011714', 'K131353', '1405830166', '220454',
       '2135403', '3/37/2781', '3/68/0129', '11/851/0022', 'C201501',
       'C201502', '3/59/1773', '11/973/94', '11/326/19', '11/11711/38',
       '651', '11/11711/86 (SV)', '5/0048/0022', '002/1352/0077',
       '3/37/0281', '3/68/0248', '3/59/1150', '3/59/1327', '3/37/0021',
       '1104362909', '1302911347', '3/68/0141', '11/194/07', '3/37/0170',
       'HDOA #210391', 'HDOA #210363', '09/030/273', '3/37/4468',
       '010/0357/0085', '123', '444', '16', '999', '11/11711/27',
       '11/11711/84 (S.V.S.A)', '11/049/0093', '3/37/2864', '3/68/0145',
       '3/259/0267', '1489', '2200301', '3/37/2759', '11/23/0513',
       '002/1660/0047', '09/0488/1', '11/23/0578', '002/1495/0695',
       '3015388', '015/1691/065', '3/320/0025', '3/37/1765',
       '033/006/007', '2676', '1104373099', '11/23/0934', '9/29/1991',
       '11/43367/27', '11/973/276', '11/23/0693', '11/23/0632',
       '11/23/0690', '11/23/0369', '09/134/17', '002/1660/0048',
       '5300343627999', '3/37/0127', 'C21', '11/972/34', '3/201/1817',
       'KP010914', 'KF010914', '3/332/0028', '1104289425', '1302910536',
       '3/79/0334', '3/37/0767', '2135401', '29', 'HDOA 210688',
       '09/0488/001', '3/01/6894', '002/4542/0213', 'C25', 'C20',
       '703805790', '793', '009/0060/44/1', '1506622904', 'F-30002939',
       '2889', '016/2484/05', '3/68/0152', '3/037/2273', '002/4542/0190',
       '015/0826/0516', 'Thailand', 'C37', '5/0048/0125', '016/2022/0008',
       '2', '3/68/0160', '3/68/0004', '1405818311',
       '703815218/703815215/703815197', '3/37/1435', '002/1251/0359',
       '13/111/097', '11/23/0146', 'C26', 'C35', '002/4177/0039',
       '11/23/0633', '3/68/0162', '11/426/2', '1702773555', '1206966823',
       'PCO-031106/7', '11/08/88/11/08/67', '002/1352/0099', '3/37/0582',
       '2135402', '11/0052/0538', '11/23/0639', '11/23/0366',
       '11/23/0400', '11/43367/12', '3/37/4434', 'GOP', '11/023/0024',
       '002/1251/0228', '030/0595/0128', '3/37/2044', '3252',
       '1104558673', '120706171/1207106169', '125464', '3/59/0782',
       '002/1251/185', '3/68/0066', '3/68/0262', '13/111/022',
       '02/143/0/0044', '5/025/0294', '5/423/0127', '002/1660/0107',
       '002/4542/0478', '11/52/349', 'C22', '002/1660/0065', '11/972/28',
       '016/2022/0010', '3/037/996', '11/23/1015', '68/0220',
       '11/9768/02', '1702806437', '11/23/0394', '002/1251/0243',
       '002/1251/0247', '3/59/0787', '002/1566/0003', '11/973/158', '391',
       '13/63/206', '1104387103', 'KF3150140', '842046', '11/11711/19',
       '009/0060/45/2', '1102751473', '3/68/0088', '3/37/0663',
       '002/1251/0183', '3/37/1979', '13/111/054', '16042', 'CA058',
       '3881832/1412427', '49881', '11873168', '002/4542/0274', 'C33',
       '3/68/0144', '1702764973', '11/00183/00020', '3196666',
       '70381402/70381402/703815394', '3/68/0154', '03/05/0846',
       '5/019/0060', 'C19', '3/59/1656', '5/025/0101', '230035',
       '1104362837', '1102751467', '2200302', '13/111/024', 'CA006',
       '105', 'C42', 'C120', '10704180', '5/0048/0144', '13/123/306',
       '3/37/2863', '??', '1104355254', '002/1251/0237', '002/1251/0240',
       '11/08/1990', '001/1251/0253', '11/23/0238', '3/37/2782',
       '11/23/0515', '09/032/86', '11/973/59', 'C13', '17/176/0125B',
       '13/137/004', '1700920709', '1702772190', '1104402366',
       '002/1241/0244', '3/068/141', '02/0143/0/0292', '015/1969/008',
       '11/23/0507', 'unspecified', '13/63/301', '5/019/0118', '15041753',
       '13/111/311', '0016/2814/0002', '3/37/2547', 'KF315210',
       '002/1352/0159', '11/23/0397', '1506543018', '1104363377',
       '002/1251/0361', '3/68/0206', 'HDOA 210281', '11/23/0514', 'C15',
       '2/1495/529', '1702772155', '1104372561',
       '2037240/2037150/1400213685', '3/68/0059', '3/37/2930',
       '11/23/0640', '11/23/0701', '033/0004/0191', '017/001/534', 'C001',
       'C39', '002/4177/0161', '15/1595/0021', '13/111/192', '5/025/0135',
       '016/2022/0009', '2496', '11/9768/01', '1506803385', '2200305',
       '11/23/0368', '5/025/024/25', 'C30', '002/1660/0058', '11/23/1014',
       'Thailand/Organic/FT/Peaberry/Crop 2011P', '11/23/0688',
       '017/053/0211/017/053/0212', '13/111/083', '11/23/0367',
       '5/545/0006', 'C18', '11/951/388', '002/135/2/0276', '1506811628',
       '1506546082', '1302919531', 'na', '11/23/0239', '11/326/14',
       '002/1495/0134', '13/63/204', '0016/2814/0001', '030/0218/2662',
       '11/9772/3', '1702771645', 'F30002939', '3/68/0027', '3/68/0130',
       'HDOA 210520', '3/37/0059', '13/111/084', '13/63/318',
       '002/135/2/0076', '123/300/01', '13/01/0556',
       '002/1566/0003        ', '017/001/1214', 'C38', '1507169991',
       '017/053/0134', 'A057', '13/111/037', 'C16', '5/0048/0126',
       '002/454/2/0379', '11/183/25', '002/1251/0182', '010/0475/0522',
       '017/001/652', 'C006', '5/545/0005', '1405833052/1405833062',
       '1955', '2200304', '002/4542/0044', '002/4542/0966', '11/23/0506',
       '3/37/4378', '11/23/0706', '13/132/92', '002/4542/0275', 'C23',
       '10589010', '1506558878', '11/23/0689', 'KP121714', 'C002',
       '002/135/2/0075', '17/009/0057', '11/972/29', '1104386282',
       '11/873/054', '1506717737', '1201255296', '2200303', '3/068/0123',
       '002/4542/0021', 'Unspecified', '017/001/1066', '13/111/035',
       '5/562/0014', '1401325570/1405822583/1405822338', 'None exists',
       '2131202', 'non', '015/1691/006', '5/025/0048', 'C17',
       '14/3/79/1034', '11/23/0233', '11/23/0240', '3/37/1980',
       '017/053/0046', 'C28', '13/123/238', '11/52/121', 'HDOA 210282',
       '11/15/0293', '13/154/234', 'not applicable', '002/4542/0049',
       '11/951/136', '002/135/2/0182', '1405793051', '13/63/60', 'CNY',
       '1405675414', '027/01/601', 'A053', '11/23/0795', '2135405',
       '010/0058', '002/143/0/0058', '017/117/018', 'KPP021114',
       '11/23/1972', '1702801679', '017/053/0125', '13/63/70',
       '11/23/1170', '1104362940', '1405791535', '1104367469',
       '11/23/0582', '002/1352/0226', '17', '1401045726', '017/001/1638',
       '0016/2050/0001', '03/01/2700', 'KP022414', '1506729960',
       '017/191/488', '1104276076', 'HDOA 220468 Kona Prime', '10703510',
       '030/0595/0508', '5/066/038', '1405811686',
       'FINCA MEDINA 11/11711/01-LOGO APCA', '1506622214', '11/23/0508',
       '9', '11/23/0957', '1702807163', '1104363350', '1104379888',
       '3/68/0153', '11/194/0008', '017/176/160', '68/0197', '145092',
       '11/23/0358', '3/279/390', '1104340088', '1104275271',
       '11/23/0122', '11/23/0168', '2728', '016/2362/0057', '1405792893',
       '1207093598', '13/117/87', '030/0582/0050', '2074632', 'F07016865',
       '017/053/0211/053/0212', 'Specialty Coffee Association of America',
       '11/23/1020', '11042707999', 'LOUIS88', '1104374276', '017/053',
       '1506502938', '703817078/703817042/700137443', 'HDOA 210542',
       '0016/2795/0008', '1506868415', 'K#1/21614', '11/23/0334',
       '11/23/0101', 'KP120314', '2209401 KONA PRIME', '1104341113',
       '13/117/88', 'KF 21614', '1506558883', '03/01/1632', '5/545/0007',
       '11/23/0121', '16039', '11/23/0333', 'KP3150140', '110548082',
       '11/426/1', '1506558882', '30', '14/7/2015/172', '016/2362/0051',
       '11/23/01', 'KPBP 21114', 'Specialty Coffee Association',
       '1405792248', '1104372556', '11/23/0768', '2670', 'F07008657',
       'KPBP 022414', '11/23/0796', '1104820070', '220456',
       '0016/2722/0001', '5/545/0015', '11111', '1104351023',
       '0016/2847/0001', '1104328663', '11/853/165', '14/1148/2017/21',
       '0000', '14/1148/2017/18', '14/1148/2016/17', '14/1148/2016/12',
       '14/1118/2014/0087'], dtype=object)

In [57]:
# ICO codes are numerical; that is why I replace each value that contains a letter with "Incorrect number"
ico_pattern = r'^\d+/\d+/\d+$'
coffee_data['ico_number'] = coffee_data['ico_number'].apply(
    lambda x: x if re.match(ico_pattern, x) else "Incorrect format"
)

In [58]:
coffee_data['ico_number'].unique()

array(['Incorrect format', '5/562/0015', '002/1251/0073', '13/111/053',
       '002/1251/0068', '01/011/512', '002/1352/0045', '002/1251/0071',
       '11/23/0252', '3/68/0215', '11/1886/03', '11/853/155',
       '030/0537/2066', '09/060/24', '11/52/492', '002/1251/0072',
       '5/562/0006', '5/562/0016', '37/672/0017', '010/0001/0022',
       '11/23/0177', '3/68/0102', '3/79/0634', '11/30/0593', '3/59/3115',
       '3/59/0951', '3/37/1829', '37/672/0016', '002/1251/0242',
       '016/2484/04', '11/194/0014', '3/37/0277', '3/37/4824',
       '3/37/0416', '002/1251/0070', '002/1251/0066', '37/00395/0335',
       '13/63/174', '9/29/1986', '1/053/0222', '09/392/69', '5/423/0128',
       '11/08/0109', '5/114/0171', '5/0048/0052', '5/1106/0011',
       '3/79/0543', '11/23/1088', '11/1886/02',
       '703816889/108282/703816891', '3/37/1724', '3/37/1291',
       '11/972/26', '11/23/0291', '3/79/0542', '3/37/0930', '3/68/0224',
       '3/68/0005', '002/1251/0069', '002/1251/0076', '5/0015/0029',
       '5/114/0170', '11/23/0398', '11/326/06', '5/0015/0231',
       '3/59/0318', '3/37/2940', '13/111/023', '03/05/0845', '13/111/032',
       '3/37/1704', '3/59/2235', '3/68/0225', '002/1251/0360',
       '11/897/10', '3/59/3461', '11/11711/59', '11/52/709', '3/37/0637',
       '3/37/4823', '3/59/2270', '11/23/0561', '3/68/0290', '11/23/0365',
       '3/37/3825', '5/818/0450', '11/52/1170', '11/752/01', '11/23/0335',
       '3/37/4173', '017/176/165', '002/1495/0607', '5/025/0111',
       '11/43984/0001', '37/0569/2730', '11/9772/2', '3/68/0019',
       '11/853/053', '3/59/0503', '11/23/0178', '3/37/0118',
       '010/0343/0083', '13/111/038', '11/52/841', '11/23/0535',
       '11/23/0465', '3/37/2301', '002/4177/0121', '37/0569/2347',
       '002/1660/0079', '016/1273/101', '002/1660/0105', '3/59/1772',
       '03/01/5274', '3/37/0985', '3/79/0635', '3/59/2888', '3/37/2112',
       '5/025/0249', '11/11711/60', '002/4177/0150', '002/1660/0066',
       '5/0048/0145', '11/23/0436', '3/68/0221', '11/23/0464',
       '002/1352/0052', '37/0985/4132', '3/59/0075', '3/37/1510',
       '3/59/0708', '3/37/1419', '3/259/0471', '3/68/0049', '3/68/0260',
       '11/10170/005', '3/059/1329', '3/68/0124', '002/1660/0080',
       '37/0985/4045', '017/001/1412', '002/1660/0106', '5/025/0109',
       '3/259/1444', '11/52/380', '3/68/0021', '3/37/2865', '11/23/0634',
       '11/23/0420', '3/68/0045', '11/183/22', '11/23/0933',
       '11/11711/08', '3/37/2548', '3/37/0636', '016/2028/042',
       '3/79/0828', '3/37/1824', '002/1251/0181', '3/59/1695',
       '5/025/0250', '3/59/1919', '11/23/0145', '3/37/0634', '3/68/0068',
       '11/023/0025', '3/79/2009', '13/111/240', '3/68/0161', '3/68/0183',
       '11/752/02', '3/37/0666', '11/23/0237', '3/59/0504', '11/23/0696',
       '3/59/2318', '5/025/0032', '9/391/73', '3/59/2236',
       '002/4542/0886', '11/23/0562', '11/11711/6', '11/23/1040',
       '3/68/0147', '03/01/0424', '3/37/3729', '3/37/2623', '3/68/0103',
       '5/562/0013', '5/0048/0023', '030/0695/1742', '3/59/1326',
       '11/23/0419', '3/68/0133', '5/139/0050', '11/973/152',
       '035/170/5061178', '002/4542/0189', '3/79/1818', '11/23/0767',
       '002/1251/0241', '3/68/0089', '3/37/0661', '3/68/0205',
       '3/68/0107', '3/068/0108', '11/23/0673', '11/11711/58',
       '13/63/214', '9/392/68', '11/11711/1', '11/23/2004',
       '37/0843/3305', '3/37/0119', '13/01/2369', '13/111/193',
       '11/326/10', '3/37/1691', '3/68/0140', '002/1251/0250',
       '002/1251/0245', '11/26/0236', '002/1251/0075', '9/29/1990',
       '010/0182/0008', '3/59/1694', '3/37/0278', '002/1660/0049',
       '002/4177/0164', '002/4542/0477', '002/1660/0064', '05/0048/0171',
       '3/37/2781', '3/68/0129', '11/851/0022', '3/59/1773', '11/973/94',
       '11/326/19', '11/11711/38', '5/0048/0022', '002/1352/0077',
       '3/37/0281', '3/68/0248', '3/59/1150', '3/59/1327', '3/37/0021',
       '3/68/0141', '11/194/07', '3/37/0170', '09/030/273', '3/37/4468',
       '010/0357/0085', '11/11711/27', '11/049/0093', '3/37/2864',
       '3/68/0145', '3/259/0267', '3/37/2759', '11/23/0513',
       '002/1660/0047', '09/0488/1', '11/23/0578', '002/1495/0695',
       '015/1691/065', '3/320/0025', '3/37/1765', '033/006/007',
       '11/23/0934', '9/29/1991', '11/43367/27', '11/973/276',
       '11/23/0693', '11/23/0632', '11/23/0690', '11/23/0369',
       '09/134/17', '002/1660/0048', '3/37/0127', '11/972/34',
       '3/201/1817', '3/332/0028', '3/79/0334', '3/37/0767',
       '09/0488/001', '3/01/6894', '002/4542/0213', '016/2484/05',
       '3/68/0152', '3/037/2273', '002/4542/0190', '015/0826/0516',
       '5/0048/0125', '016/2022/0008', '3/68/0160', '3/68/0004',
       '703815218/703815215/703815197', '3/37/1435', '002/1251/0359',
       '13/111/097', '11/23/0146', '002/4177/0039', '11/23/0633',
       '3/68/0162', '11/426/2', '002/1352/0099', '3/37/0582',
       '11/0052/0538', '11/23/0639', '11/23/0366', '11/23/0400',
       '11/43367/12', '3/37/4434', '11/023/0024', '002/1251/0228',
       '030/0595/0128', '3/37/2044', '3/59/0782', '002/1251/185',
       '3/68/0066', '3/68/0262', '13/111/022', '5/025/0294', '5/423/0127',
       '002/1660/0107', '002/4542/0478', '11/52/349', '002/1660/0065',
       '11/972/28', '016/2022/0010', '3/037/996', '11/23/1015',
       '11/9768/02', '11/23/0394', '002/1251/0243', '002/1251/0247',
       '3/59/0787', '002/1566/0003', '11/973/158', '13/63/206',
       '11/11711/19', '3/68/0088', '3/37/0663', '002/1251/0183',
       '3/37/1979', '13/111/054', '002/4542/0274', '3/68/0144',
       '11/00183/00020', '70381402/70381402/703815394', '3/68/0154',
       '03/05/0846', '5/019/0060', '3/59/1656', '5/025/0101',
       '13/111/024', '5/0048/0144', '13/123/306', '3/37/2863',
       '002/1251/0237', '002/1251/0240', '11/08/1990', '001/1251/0253',
       '11/23/0238', '3/37/2782', '11/23/0515', '09/032/86', '11/973/59',
       '13/137/004', '002/1241/0244', '3/068/141', '015/1969/008',
       '11/23/0507', '13/63/301', '5/019/0118', '13/111/311',
       '0016/2814/0002', '3/37/2547', '002/1352/0159', '11/23/0397',
       '002/1251/0361', '3/68/0206', '11/23/0514', '2/1495/529',
       '2037240/2037150/1400213685', '3/68/0059', '3/37/2930',
       '11/23/0640', '11/23/0701', '033/0004/0191', '017/001/534',
       '002/4177/0161', '15/1595/0021', '13/111/192', '5/025/0135',
       '016/2022/0009', '11/9768/01', '11/23/0368', '002/1660/0058',
       '11/23/1014', '11/23/0688', '13/111/083', '11/23/0367',
       '5/545/0006', '11/951/388', '11/23/0239', '11/326/14',
       '002/1495/0134', '13/63/204', '0016/2814/0001', '030/0218/2662',
       '11/9772/3', '3/68/0027', '3/68/0130', '3/37/0059', '13/111/084',
       '13/63/318', '123/300/01', '13/01/0556', '017/001/1214',
       '017/053/0134', '13/111/037', '5/0048/0126', '11/183/25',
       '002/1251/0182', '010/0475/0522', '017/001/652', '5/545/0005',
       '002/4542/0044', '002/4542/0966', '11/23/0506', '3/37/4378',
       '11/23/0706', '13/132/92', '002/4542/0275', '11/23/0689',
       '17/009/0057', '11/972/29', '11/873/054', '3/068/0123',
       '002/4542/0021', '017/001/1066', '13/111/035', '5/562/0014',
       '1401325570/1405822583/1405822338', '015/1691/006', '5/025/0048',
       '11/23/0233', '11/23/0240', '3/37/1980', '017/053/0046',
       '13/123/238', '11/52/121', '11/15/0293', '13/154/234',
       '002/4542/0049', '11/951/136', '13/63/60', '027/01/601',
       '11/23/0795', '017/117/018', '11/23/1972', '017/053/0125',
       '13/63/70', '11/23/1170', '11/23/0582', '002/1352/0226',
       '017/001/1638', '0016/2050/0001', '03/01/2700', '017/191/488',
       '030/0595/0508', '5/066/038', '11/23/0508', '11/23/0957',
       '3/68/0153', '11/194/0008', '017/176/160', '11/23/0358',
       '3/279/390', '11/23/0122', '11/23/0168', '016/2362/0057',
       '13/117/87', '030/0582/0050', '11/23/1020',
       '703817078/703817042/700137443', '0016/2795/0008', '11/23/0334',
       '11/23/0101', '13/117/88', '03/01/1632', '5/545/0007',
       '11/23/0121', '11/23/0333', '11/426/1', '016/2362/0051',
       '11/23/01', '11/23/0768', '11/23/0796', '0016/2722/0001',
       '5/545/0015', '0016/2847/0001', '11/853/165'], dtype=object)

In [63]:
coffee_data['ico_number'].value_counts()

ico_number
Incorrect format    731
002/4177/0150         7
002/1660/0105         7
002/1660/0080         6
13/111/053            5
                   ...
11/23/0333            1
5/545/0007            1
03/01/1632            1
11/23/0334            1
002/1251/0068         1
Name: count, Length: 503, dtype: int64

In [66]:
coffee_data.company.value_counts(dropna = False)

company
NaN                                      209
unex guatemala, s.a.                      86
ipanema coffees                           50
exportadora de cafe condor s.a            40
racafe & cia s.c.a                        40
                                        ...
kasozi coffee farmers association          1
nitubaasa ltd                              1
mannya coffee project                      1
yidnekachew debessa coffee plantation      1
global opportunity fund                    1
Name: count, Length: 282, dtype: int64

In [68]:
coffee_data.company = coffee_data.company.str.upper()

In [71]:
coffee_data[coffee_data.company.isna()]

,species,owner,country_of_origin,farm_name,mill,ico_number,company,altitude,region,producer,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
2,Arabica,GROUNDS FOR HEALTH ADMIN,Guatemala,"san marcos barrancas ""san cristobal cuch",Unknown,Incorrect format,NaN,1600 - 1800 m,NaN,NaN,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
5,Arabica,JI-AE AHN,Brazil,Unspecified,Unknown,Incorrect format,NaN,NaN,NaN,NaN,...,Bluish-Green,1,"September 3rd, 2014",Specialty Coffee Institute of Asia,726e4891cf2c9a4848768bd34b668124d12c4224,b70da261fcc84831e3e9620c30a8701540abc200,m,NaN,NaN,NaN
7,Arabica,ETHIOPIA COMMODITY EXCHANGE,Ethiopia,aolme,C.P.W.E,Incorrect format,NaN,1570-1700,oromia,Bazen Agricultural & Industrial Dev't Plc,...,NaN,0,"September 2nd, 2011",Ethiopia Commodity Exchange,a176532400aebdc345cf3d870f84ed3ecab6249e,61bbaf6a9f341e5782b8e7bd3ebf76aac89fe24b,m,1570.0,1700.0,1635.0
8,Arabica,ETHIOPIA COMMODITY EXCHANGE,Ethiopia,aolme,C.P.W.E,Incorrect format,NaN,1570-1700,oromiya,Bazen Agricultural & Industrial Dev't Plc,...,NaN,0,"September 2nd, 2011",Ethiopia Commodity Exchange,a176532400aebdc345cf3d870f84ed3ecab6249e,61bbaf6a9f341e5782b8e7bd3ebf76aac89fe24b,m,1570.0,1700.0,1635.0
13,Arabica,GROUNDS FOR HEALTH ADMIN,United States (Hawaii),arianna farms,Unknown,Incorrect format,NaN,2000 ft,kona,"Robert, Sharon, Arianna Wood",...,NaN,2,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,ft,609.6,609.6,609.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,Arabica,JORGE OCTAVIO ESCAMILLA PRADO,Mexico,las ceibas,CATUAI AMARILLO SSS,Incorrect format,NaN,1140,"chocaman, veracruz",JORGE OCTAVIO ESCAMILLA PRADO,...,Green,11,"September 10th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,1140.0,1140.0,1140.0
1289,Arabica,MYRNA ROXANA GALVEZ GONZALEZ,Mexico,la marina-el orizabeño,BENEFICIO DE CAFÉ TECOXOLCO S. DE R.L. DE C.V.,Incorrect format,NaN,1200,xalapa,MYRNA ROXANA GÁLVEZ GONZÁLEZ,...,NaN,27,"September 17th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,1200.0,1200.0,1200.0
1290,Arabica,EUGENE HOLMAN PEW,Mexico,rancho vigia,RANCHO VIGIA,Incorrect format,NaN,1250,coatepec,EUGENE HOLMAN PEW,...,Green,19,"August 1st, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,1250.0,1250.0,1250.0
1297,Arabica,MYRIAM KAPLAN-PASTERNAK,Haiti,2000 farmers,COOPERATIVE AGRO-INDUSTRIELLE DE MARMELA,Incorrect format,NaN,640m-1400m,marmelade,Asosyasyon Plantè Kafe Krètapen (APCAP) ;Asosy...,...,NaN,0,"August 22nd, 2012",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,640.0,1400.0,1020.0
1300,Arabica,RICARDO AARON SAMPIERI MARINI,Mexico,la morena,"TLAMATOCA, HUTUSCO, VER.",Incorrect format,NaN,1800,veracruz,RICARDO AARON SAMPIERI MARINI,...,Green,0,"July 11th, 2013",AMECAFE,59e396ad6e22a1c22b248f958e1da2bd8af85272,0eb4ee5b3f47b20b049548a2fd1e7d4a2b70d0a7,m,1800.0,1800.0,1800.0

In [77]:
coffee_data.company = coffee_data.company.fillna("Not mentioned")

In [79]:
coffee_data.company.value_counts(dropna = False)

company
Not mentioned                            209
UNEX GUATEMALA, S.A.                      86
IPANEMA COFFEES                           50
EXPORTADORA DE CAFE CONDOR S.A            40
RACAFE & CIA S.C.A                        40
                                        ...
KASOZI COFFEE FARMERS ASSOCIATION          1
NITUBAASA LTD                              1
MANNYA COFFEE PROJECT                      1
YIDNEKACHEW DEBESSA COFFEE PLANTATION      1
GLOBAL OPPORTUNITY FUND                    1
Name: count, Length: 282, dtype: int64

In [80]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   species                1339 non-null   category
 1   owner                  1339 non-null   object
 2   country_of_origin      1339 non-null   object
 3   farm_name              1339 non-null   object
 4   mill                   1339 non-null   object
 5   ico_number             1339 non-null   object
 6   company                1339 non-null   object
 7   altitude               1113 non-null   object
 8   region                 1280 non-null   object
 9   producer               1107 non-null   object
 10  number_of_bags         1339 non-null   int64
 11  bag_weight             1339 non-null   object
 12  in_country_partner     1339 non-null   object
 13  harvest_year           1292 non-null   object
 14  grading_date           1339 non-null   object
 15  owner_1                1332 non-null   object
 16  variety                1113 non-null   object
 17  processing_method      1169 non-null   object
 18  aroma                  1339 non-null   float64
 19  flavor                 1339 non-null   float64
 20  aftertaste             1339 non-null   float64
 21  acidity                1339 non-null   float64
 22  body                   1339 non-null   float64
 23  balance                1339 non-null   float64
 24  uniformity             1339 non-null   float64
 25  clean_cup              1339 non-null   float64
 26  sweetness              1339 non-null   float64
 27  cupper_points          1339 non-null   float64
 28  total_cup_points       1339 non-null   float64
 29  moisture               1339 non-null   float64
 30  category_one_defects   1339 non-null   int64
 31  quakers                1338 non-null   float64
 32  color                  1069 non-null   object
 33  category_two_defects   1339 non-null   int64
 34  expiration             1339 non-null   object
 35  certification_body     1339 non-null   object
 36  certification_address  1339 non-null   object
 37  certification_contact  1339 non-null   object
 38  unit_of_measurement    1339 non-null   object
 39  altitude_low_meters    1109 non-null   float64
 40  altitude_high_meters   1109 non-null   float64
 41  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(22)
memory usage: 430.5+ KB

In [82]:
coffee_data.altitude.unique()

array(['1950-2200', '1600 - 1800 m', '1800-2200', nan, '1570-1700',
       '1795-1850', '1855-1955', 'meters above sea level: 1.872',
       'meters above sea level: 1.943', '2000 ft',
       'meters above sea level: 2.080', '1200-1800m', '1450',
       '1700-2000m', 'meters above sea level: 2.019', '1300 msnm', '1320',
       'meters above sea level: 2.112', '1250m', '1950', '1400', '1200',
       '1300', '1750-1800', '1800', 'meters above sea level: 1.941',
       '1.2', '1000 m', '1754', '900-1500m', '1520m-2200m', '1400-1900m',
       '1500-2000 m', '1400ft', '1400-1900', '1800 msnm', '1600',
       '1800-2000', '5000', '4650', '1700 mts', '1500 meters',
       '1300~1400 m.s.l', '1680', '1900m', '5600-5760 metros', '1400 m',
       '1700', '1770', 'above 1600 m', 'above 1200 m', '1550 msnm',
       '1550', '1250-1400 meter', '1400 msm', '2.560 msnm', '2136 msnm',
       '1900', '-1', '1580', '1100m', '1400 masl', '3500-5200 feet',
       'de 1600 a 1950 msnm', '800 m', '1620m', '1200m', '350',
       '1450 msnm', '1200 mts', '800-1050m', '1350', '170', '1150',
       '1750', '1750m', '2000', '4300', '1700-1850m', '1500', '5000 ft.',
       '4000 psn', '1600 a 1900 msnm', '1750 msnm', '1450 ~ 1700 m',
       '1300m', 'above 1100m', '2000 m', 'mmm', 'test', '900', '442 msnm',
       '1200m to 1350m', '900-1200m', '3600-6200 ft', '4400-4700 ft',
       '1000', '2560', '3607', '4000 psnm', '1170', '1700m', '3664',
       '1565', '3280', 'de 900 a 1100 msnm', '1850', '1545-1668 masl',
       '1530', "approx. 1'500 metres a.s.l.", '894m - 1183m',
       '1500-1700m', '442', '968', '1480', '1800m', '5440 - 5760 metros',
       '1550 m', '1260', '1700 msnm', '1650', '890', '934', '950公尺',
       '2527', '1', '480-570m', '1650-1703', '1200-1400',
       '800 meters above sea level', '1218', '1.250 m', '4921ft', '750',
       '2800 ft', '1500-1600', '700', '1300 mts', '1600 m.s.n.m',
       '1600 msnm', '1250', '800++', '1550-1700m', '4451 metros',
       '1800 - 2000', '1100', '1200-1600masl', '3702',
       'de 1.600 a 1.950 msnm', '1799', '4000', '1400m',
       '1600 on average', '1850 msnm', '1400 mts', '940', '4600 ft.',
       '439', '1330', '1813', '1500 msnm', '900-1200mtr', '1227',
       '1650 msnm', '1100-1300', '4200 feet', '1000 msnm', '1880', '2100',
       '1261', '800公尺', '1483', '175', '1600-1800msnm', '1880 msnm',
       '1800 m.s.n.m', '1901', '16.8', '1500msnm', '1400-1900 psn',
       "approx.1'500 metres a.s.l.", '1653', '1450 msnn', '5000 pies',
       '532', '1089', '1380', '1000m', '950m', '900m', '1850 m', '905',
       '700-800m', '1300 m', 'de 1.600 a 1.950 msn', '1300-1400m', '894',
       '872', '1473', '1645', '1300 a 1800 metros sobre el nivel del mar',
       '4500 pies', '900-1100', '1600 - 1950 msnm', '1500-1750 msnm',
       '4500', '1050 - 1850 msnm', '775', '1200 masl',
       '1600 + meters above sea level', '1059', '1300 meters',
       '11000 metros', '5440-5760 metros', '1248', '1040m', '1040',
       '4000psn', '1200-2000m', '1200 m', '1800 mts',
       '1400 meter above sea level', '518', '650', '1442 m', '1.65',
       '1400 thru 1850', '1200公尺', '1296', '1400- 1900', '1240 m', '950',
       '1800 meters (5900', '1050', '200 m', '1200-1300m dpl',
       '1400-1500 m', '1317', '900-1050m', '1679', '2285', 'huanuco',
       '1560', '1750 m.s.n.m', '1396', '982', '1268', '5500 metros',
       '1450 m', '600 m', '5500-6000 psnm', '441', '1200 a 1400', '1180m',
       '650 m', '1338', '533', '4563', '1500-1800', '1200-1600m', '1144',
       '1200-1400 masl', '1500 - 1700', '1.3', '944', '1300- 1400',
       '2500m', '600m', '1400 m.s.n.m.', '600-700 m', '1050m', '1020',
       '1300 a 1800 mtrs. a nivel del mar', '1877', '1000-1500m', '981',
       '690', '973', '4001', '1350-1500', '1400 msnm', '700m', '1556m',
       '1550 meters', 'de 1.600 a 1950 msnm', '900-950m',
       '1600-1800 msnm', '774', '150 m', '750 m', '190164', '800',
       '850 m', '4500-6000 feet', '160-200m', '4000 ft', '1200 msm',
       '1599m', '900 m', '400-1250m', '1.25', '1050 - 1850', '110公尺',
       '1422', '1550 mts.', '1550 meter', '763', '1130', '680',
       '1400 msn', '5000 f', '100/2000', '1450 mals', '990-1000m', '0',
       '695', '1100 m.o.s.l.', '5600 feet', '1456', '1500 mts', '1642',
       '758m', '1350 snn', '1525 m', '1100 m', '200', '3500 ft', '550公尺',
       'between 700 and 1400 meters', '688 m', '300 m', '1186', '1210',
       '100', '3825', '1100.00 mosl', '1450 masl', '1680m',
       '~1000 meters', '1200-1500', '1.85', '4540 metros', '50', '280',
       '1250 m', '3800', '4000 p.s.n.m.', '6100 metros', '600公尺', '1450m',
       '995', '3000 ft', '4287', '900 m.s.n.m.', '700 m', '808',
       '1100 - 1275 mts', '850公尺', '250 m', '3845', '1300 to 1500 meters',
       '1901.64', '800-1200', '500-700m', '1022', '975', '1264',
       '3500 - 5200 feet', '700m公尺', '850', '12oo', '800m', '1600 meters',
       '4000 p.s.n.m', '1200 meters', '750-800 m', '900-1500 masl',
       '3500', '1000+ meters', '1280', '1140', '640m-1400m',
       '1000 meters', '~350m', '1488', '3170', '1212', '1200-1300',
       "3000'", '750m', '3140', '900-1300', '1095', '1367', '1745', '40',
       '795 meters'], dtype=object)

In [83]:
# Define all replacement rules in one place
unit_map = {
    "msnm": "m",
    "m.s.n.m": "m",
    "masl": "m",
    "mts": "m",
    "mtrs": "m",
    "meter": "m",
    "meters": "m",
    "metros": "m",
    "公尺": "m",
    "pies": "ft",
    "pies.": "ft",
    "ft.": "ft",
    "feet": "ft",
    "ft": "ft",  # normalize even this
    "psn": "ft",
    "psnm": "ft",
    "p.s.n.m.": "ft",
    "p.s.n.m": "ft"
}

def normalize_units(value):
    for key, val in unit_map.items():
        value = value.replace(key, val)
    return value

def clean_altitude(value):
    if pd.isnull(value):
        return np.nan

    value = str(value).lower()

    # Normalize units
    value = normalize_units(value)

    # Clean approx and extra symbols
    value = re.sub(r"approx(?:\.|imately)?", "", value)
    value = re.sub(r"[~']", "", value)
    value = re.sub(r"[^0-9\.\-\sftm]", "", value)  # remove strange symbols

    # Extract numbers
    nums = re.findall(r"\d+(?:\.\d+)?", value)
    if not nums:
        return np.nan

    nums = [float(n) for n in nums]

    # Handle ranges (take average)
    avg = sum(nums) / len(nums)

    # Check if it's in feet
    if 'ft' in value:
        avg *= 0.3048  # Convert to meters

    return round(avg, 2)

In [85]:
coffee_data.altitude = coffee_data.altitude.apply(clean_altitude)

In [86]:
coffee_data.altitude.value_counts(dropna = False)

altitude
NaN       229
1200.0     67
1100.0     54
1400.0     52
1300.0     50
         ...
1095.0      1
1367.0      1
1745.0      1
40.0        1
795.0       1
Name: count, Length: 222, dtype: int64

In [88]:
coffee_data.altitude.astype(float)

0       2075.0
1       2075.0
2       1700.0
3       2000.0
4       2075.0
         ...
1334       NaN
1335      40.0
1336     795.0
1337       NaN
1338       NaN
Name: altitude, Length: 1339, dtype: float64