In [1]:
%matplotlib inline

In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Homework 1
## Data Tidying and Cleaning

In [3]:
# Reading the dataset... Naming it coffee_data
## The "../" helps referring to the parent folder of the current one.
coffee_data = pd.read_csv("../data/merged_data_cleaned.csv")

In [4]:
coffee_data

,Unnamed: 0,Species,Owner,Country.of.Origin,Farm.Name,Lot.Number,Mill,ICO.Number,Company,Altitude,...,Color,Category.Two.Defects,Expiration,Certification.Body,Certification.Address,Certification.Contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
0,0,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,0,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
1,1,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,1,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
2,2,Arabica,grounds for health admin,Guatemala,"san marcos barrancas ""san cristobal cuch",NaN,NaN,NaN,NaN,1600 - 1800 m,...,NaN,0,"May 31st, 2011",Specialty Coffee Association,36d0d00a3724338ba7937c52a378d085f2172daa,0878a7d4b9d35ddbf0fe2ce69a2062cceb45a660,m,1600.0,1800.0,1700.0
3,3,Arabica,yidnekachew dabessa,Ethiopia,yidnekachew dabessa coffee plantation,NaN,wolensu,NaN,yidnekachew debessa coffee plantation,1800-2200,...,Green,2,"March 25th, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1800.0,2200.0,2000.0
4,4,Arabica,metad plc,Ethiopia,metad plc,NaN,metad plc,2014/2015,metad agricultural developmet plc,1950-2200,...,Green,2,"April 3rd, 2016",METAD Agricultural Development plc,309fcf77415a3661ae83e027f7e5f05dad786e44,19fef5a731de2db57d16da10287413f5f99bc2dd,m,1950.0,2200.0,2075.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1334,1334,Robusta,luis robles,Ecuador,robustasa,Lavado 1,our own lab,NaN,robustasa,NaN,...,Blue-Green,1,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN
1335,1335,Robusta,luis robles,Ecuador,robustasa,Lavado 3,own laboratory,NaN,robustasa,40,...,Blue-Green,0,"January 18th, 2017",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,40.0,40.0,40.0
1336,1336,Robusta,james moore,United States,fazenda cazengo,NaN,cafe cazengo,NaN,global opportunity fund,795 meters,...,NaN,6,"December 23rd, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,795.0,795.0,795.0
1337,1337,Robusta,cafe politico,India,NaN,NaN,NaN,14-1118-2014-0087,cafe politico,NaN,...,Green,1,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN
1338,1338,Robusta,cafe politico,Vietnam,NaN,NaN,NaN,NaN,cafe politico,NaN,...,NaN,9,"August 25th, 2015",Specialty Coffee Association,ff7c18ad303d4b603ac3f8cff7e611ffc735e720,352d0cf7f3e9be14dad7df644ad65efc27605ae2,m,NaN,NaN,NaN

In [5]:
# Size of the dataset
coffee_data.shape

(1339, 44)

In [6]:
# Columns (variables / features) in the dataset
coffee_data.columns

Index(['Unnamed: 0', 'Species', 'Owner', 'Country.of.Origin', 'Farm.Name',
       'Lot.Number', 'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region',
       'Producer', 'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner',
       'Harvest.Year', 'Grading.Date', 'Owner.1', 'Variety',
       'Processing.Method', 'Aroma', 'Flavor', 'Aftertaste', 'Acidity', 'Body',
       'Balance', 'Uniformity', 'Clean.Cup', 'Sweetness', 'Cupper.Points',
       'Total.Cup.Points', 'Moisture', 'Category.One.Defects', 'Quakers',
       'Color', 'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [7]:
# Types of variables
coffee_data.dtypes

Unnamed: 0                 int64
Species                   object
Owner                     object
Country.of.Origin         object
Farm.Name                 object
Lot.Number                object
Mill                      object
ICO.Number                object
Company                   object
Altitude                  object
Region                    object
Producer                  object
Number.of.Bags             int64
Bag.Weight                object
In.Country.Partner        object
Harvest.Year              object
Grading.Date              object
Owner.1                   object
Variety                   object
Processing.Method         object
Aroma                    float64
Flavor                   float64
Aftertaste               float64
Acidity                  float64
Body                     float64
Balance                  float64
Uniformity               float64
Clean.Cup                float64
Sweetness                float64
Cupper.Points            float64
Total.Cup.Points         float64
Moisture                 float64
Category.One.Defects       int64
Quakers                  float64
Color                     object
Category.Two.Defects       int64
Expiration                object
Certification.Body        object
Certification.Address     object
Certification.Contact     object
unit_of_measurement       object
altitude_low_meters      float64
altitude_high_meters     float64
altitude_mean_meters     float64
dtype: object

In [8]:
# Checking if the column "Unnamed: 0" is the same as the "index" column
coffee_data["Unnamed: 0"].nunique()

1339

In [9]:
# Remove the unnecessary column ["Unnamed: 0"] as it is the same as the index 
# (proven by the previous row - we have 1339 unique values which is exactly the role of the index)
coffee_data = coffee_data.drop(columns = "Unnamed: 0")

In [10]:
coffee_data.columns

Index(['Species', 'Owner', 'Country.of.Origin', 'Farm.Name', 'Lot.Number',
       'Mill', 'ICO.Number', 'Company', 'Altitude', 'Region', 'Producer',
       'Number.of.Bags', 'Bag.Weight', 'In.Country.Partner', 'Harvest.Year',
       'Grading.Date', 'Owner.1', 'Variety', 'Processing.Method', 'Aroma',
       'Flavor', 'Aftertaste', 'Acidity', 'Body', 'Balance', 'Uniformity',
       'Clean.Cup', 'Sweetness', 'Cupper.Points', 'Total.Cup.Points',
       'Moisture', 'Category.One.Defects', 'Quakers', 'Color',
       'Category.Two.Defects', 'Expiration', 'Certification.Body',
       'Certification.Address', 'Certification.Contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [11]:
# See if Species can be turned into a categorical variable instead of being an object var
coffee_data.Species

0       Arabica
1       Arabica
2       Arabica
3       Arabica
4       Arabica
         ...
1334    Robusta
1335    Robusta
1336    Robusta
1337    Robusta
1338    Robusta
Name: Species, Length: 1339, dtype: object

In [12]:
coffee_data.Species.value_counts(dropna = False)

Species
Arabica    1311
Robusta      28
Name: count, dtype: int64

In [13]:
# As there are only two types of coffee species, the feature "species" can be turned into a categorical variable
coffee_data.Species = coffee_data.Species.astype("category")

In [14]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Species                1339 non-null   category
 1   Owner                  1332 non-null   object
 2   Country.of.Origin      1338 non-null   object
 3   Farm.Name              980 non-null    object
 4   Lot.Number             276 non-null    object
 5   Mill                   1021 non-null   object
 6   ICO.Number             1180 non-null   object
 7   Company                1130 non-null   object
 8   Altitude               1113 non-null   object
 9   Region                 1280 non-null   object
 10  Producer               1107 non-null   object
 11  Number.of.Bags         1339 non-null   int64
 12  Bag.Weight             1339 non-null   object
 13  In.Country.Partner     1339 non-null   object
 14  Harvest.Year           1292 non-null   object
 15  Grading.Date           1339 non-null   object
 16  Owner.1                1332 non-null   object
 17  Variety                1113 non-null   object
 18  Processing.Method      1169 non-null   object
 19  Aroma                  1339 non-null   float64
 20  Flavor                 1339 non-null   float64
 21  Aftertaste             1339 non-null   float64
 22  Acidity                1339 non-null   float64
 23  Body                   1339 non-null   float64
 24  Balance                1339 non-null   float64
 25  Uniformity             1339 non-null   float64
 26  Clean.Cup              1339 non-null   float64
 27  Sweetness              1339 non-null   float64
 28  Cupper.Points          1339 non-null   float64
 29  Total.Cup.Points       1339 non-null   float64
 30  Moisture               1339 non-null   float64
 31  Category.One.Defects   1339 non-null   int64
 32  Quakers                1338 non-null   float64
 33  Color                  1069 non-null   object
 34  Category.Two.Defects   1339 non-null   int64
 35  Expiration             1339 non-null   object
 36  Certification.Body     1339 non-null   object
 37  Certification.Address  1339 non-null   object
 38  Certification.Contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(23)
memory usage: 440.9+ KB

In [15]:
# Make the columns in a more pythonic style
coffee_data.columns = coffee_data.columns.str.lower()

In [23]:
coffee_data = coffee_data.rename(columns = lambda col: col.replace(".", "_"))

In [24]:
coffee_data.species.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1339 entries, 0 to 1338
Series name: species
Non-Null Count  Dtype
--------------  -----
1339 non-null   category
dtypes: category(1)
memory usage: 1.6 KB

In [25]:
coffee_data.columns

Index(['species', 'owner', 'country_of_origin', 'farm_name', 'lot_number',
       'mill', 'ico_number', 'company', 'altitude', 'region', 'producer',
       'number_of_bags', 'bag_weight', 'in_country_partner', 'harvest_year',
       'grading_date', 'owner_1', 'variety', 'processing_method', 'aroma',
       'flavor', 'aftertaste', 'acidity', 'body', 'balance', 'uniformity',
       'clean_cup', 'sweetness', 'cupper_points', 'total_cup_points',
       'moisture', 'category_one_defects', 'quakers', 'color',
       'category_two_defects', 'expiration', 'certification_body',
       'certification_address', 'certification_contact', 'unit_of_measurement',
       'altitude_low_meters', 'altitude_high_meters', 'altitude_mean_meters'],
      dtype='object')

In [18]:
coffee_data.owner

0                      metad plc
1                      metad plc
2       grounds for health admin
3            yidnekachew dabessa
4                      metad plc
                  ...
1334                 luis robles
1335                 luis robles
1336                 james moore
1337               cafe politico
1338               cafe politico
Name: owner, Length: 1339, dtype: object

In [49]:
# View the owners and how many times they appear in the dataset
coffee_data.owner.value_counts(dropna = False)

owner
JUAN LUIS ALVARADO ROMERO            155
RACAFE & CIA S.C.A                    60
EXPORTADORA DE CAFE CONDOR S.A        54
KONA PACIFIC FARMERS COOPERATIVE      52
IPANEMA COFFEES                       50
                                    ...
KASOZI COFFEE FARMERS ASSOCIATION      1
NITUBAASA LTD                          1
MANNYA COFFEE PROJECT                  1
YIDNEKACHEW DABESSA                    1
JAMES MOORE                            1
Name: count, Length: 316, dtype: int64

In [27]:
# It is better to upper their names
coffee_data.owner = coffee_data.owner.str.upper()

In [ ]:
coffee_data.owner

coffee_data.owner.unique()

In [47]:
# These are the records that do not have an owner but I spot something else here.
## A lot of records have a duplicate but with some little differences which come from the ico_number
coffee_data[coffee_data.owner.isna() == True]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
364,Arabica,NaN,Honduras,los hicaques,NaN,cigrah sps,13-111-240,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
459,Arabica,NaN,Honduras,los hicaques,NaN,cigrah sps,13-111-193,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
602,Arabica,NaN,Colombia,supply chain ecom cca s.a.,NaN,south huila,3-79-0334,ecom cca s.a.,1400 thru 1850,south huila,...,Blue-Green,0,"April 11th, 2013",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,1400.0,1850.0,1625.0
848,Arabica,NaN,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-311,cigrah,1350,comayagua,...,Green,4,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
882,Arabica,NaN,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-192,cigrah,1400,comayagua,...,Green,5,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.0,1400.0,1400.0
975,Arabica,NaN,Honduras,los hicaques,NaN,cigrah,13-111-037,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0
1044,Arabica,NaN,Honduras,los hicaques,NaN,cigrah,13-111-035,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0

In [51]:
coffee_data[["owner", "farm_name"]].sample(20)

,owner,farm_name
788,JULIO PEREZ HERNANDEZ,NaN
211,RACAFE & CIA S.C.A,NaN
362,THE COFFEE SOURCE INC.,several
1285,NESTOR MENDEZ GOMEZ,sierra madre
659,SHAH PLANTATIONS,shah plantation
1300,RICARDO AARON SAMPIERI MARINI,la morena
474,NUCOFFEE,fazenda do lobo
212,WAYNER JIMENEZ,los girasoles
29,"LIN, CHE-HAO KRUDE 林哲豪",tsoustructive garden 鄒築園
554,ROYAL BASE CORPORATION,"apollo co., ltd."
1335,LUIS ROBLES,robustasa
616,TAYLOR WINCH (T) LTD,ampcg
322,ROB STEPHEN,NaN
309,SAUL M. HERNANDEZ RAMIREZ,naranjal
775,ORGANIZACIONES DE PRODUCTORES DE CAFE COLIMENSE,"la calera, barranca de la leona, el nogal"
1106,"EXPORTADORA ATLANTIC, S.A.",los mesones
340,ANDREAS KUSSMAUL,exportadora café california
244,OLAM AGRO COLOMBIA,NaN
1139,KENNEDY MACHARIA,yara estate / benvar estate
717,JUAN LUIS ALVARADO ROMERO,el morito

In [63]:
# As I do not known the owner, I think that the best option is to replace the NaN values with "Unknown".
# According to my research, some coffee brands do not have an exact owner such as the coffee from Honduras - 
# actually there is no farm Ios Hicaques because that is a coffee-producing region in Honduras
coffee_data.owner = coffee_data.owner.fillna("Unknown")

In [65]:
coffee_data[coffee_data.owner == "Unknown"]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
364,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah sps,13-111-240,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
459,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah sps,13-111-193,cigrah,1350,comayagua,...,Green,3,"April 8th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
602,Arabica,Unknown,Colombia,supply chain ecom cca s.a.,NaN,south huila,3-79-0334,ecom cca s.a.,1400 thru 1850,south huila,...,Blue-Green,0,"April 11th, 2013",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,1400.0,1850.0,1625.0
848,Arabica,Unknown,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-311,cigrah,1350,comayagua,...,Green,4,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1350.0,1350.0,1350.0
882,Arabica,Unknown,Honduras,gran manzana y el aguacate,NaN,cigrah sps,13-111-192,cigrah,1400,comayagua,...,Green,5,"May 16th, 2015",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1400.0,1400.0,1400.0
975,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah,13-111-037,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0
1044,Arabica,Unknown,Honduras,los hicaques,NaN,cigrah,13-111-035,cigrah,1450 mals,central region,...,Green,1,"March 10th, 2016",Instituto Hondureño del Café,b4660a57e9f8cc613ae5b8f02bfce8634c763ab4,7f521ca403540f81ec99daec7da19c2788393880,m,1450.0,1450.0,1450.0

In [67]:
coffee_data["country_of_origin"].value_counts(dropna = False)

country_of_origin
Mexico                          236
Colombia                        183
Guatemala                       181
Brazil                          132
Taiwan                           75
United States (Hawaii)           73
Honduras                         53
Costa Rica                       51
Ethiopia                         44
Tanzania, United Republic Of     40
Uganda                           36
Thailand                         32
Nicaragua                        26
Kenya                            25
El Salvador                      21
Indonesia                        20
China                            16
India                            14
Malawi                           11
United States                    10
Peru                             10
Vietnam                           8
Myanmar                           8
Haiti                             6
Philippines                       5
United States (Puerto Rico)       4
Panama                            4
Laos                              3
Ecuador                           3
Burundi                           2
Papua New Guinea                  1
Rwanda                            1
Japan                             1
Zambia                            1
Mauritius                         1
Cote d?Ivoire                     1
NaN                               1
Name: count, dtype: int64

In [68]:
coffee_data[coffee_data["country_of_origin"].isna()]

,species,owner,country_of_origin,farm_name,lot_number,mill,ico_number,company,altitude,region,...,color,category_two_defects,expiration,certification_body,certification_address,certification_contact,unit_of_measurement,altitude_low_meters,altitude_high_meters,altitude_mean_meters
1197,Arabica,RACAFE & CIA S.C.A,NaN,NaN,NaN,NaN,3-37-1980,NaN,NaN,NaN,...,NaN,3,"February 29th, 2012",Almacafé,e493c36c2d076bf273064f7ac23ad562af257a25,70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab,m,NaN,NaN,NaN

In [70]:
# The country which is missing is Columbia according to my research
# source = "http://racafe.com.co/en/about-us/about-racafe/"
coffee_data["country_of_origin"] = coffee_data["country_of_origin"].fillna("Colombia")

In [72]:
coffee_data.loc[1197]

species                                                   Arabica
owner                                          RACAFE & CIA S.C.A
country_of_origin                                        Colombia
farm_name                                                     NaN
lot_number                                                    NaN
mill                                                          NaN
ico_number                                              3-37-1980
company                                                       NaN
altitude                                                      NaN
region                                                        NaN
producer                                                      NaN
number_of_bags                                                149
bag_weight                                                  70 kg
in_country_partner                                       Almacafé
harvest_year                                                  NaN
grading_date                                      March 1st, 2011
owner_1                                        Racafe & Cia S.C.A
variety                                                       NaN
processing_method                                             NaN
aroma                                                        6.75
flavor                                                       6.75
aftertaste                                                   6.42
acidity                                                      6.83
body                                                         7.58
balance                                                       7.5
uniformity                                                   10.0
clean_cup                                                    10.0
sweetness                                                    10.0
cupper_points                                                7.25
total_cup_points                                            79.08
moisture                                                      0.1
category_one_defects                                            0
quakers                                                       0.0
color                                                         NaN
category_two_defects                                            3
expiration                                    February 29th, 2012
certification_body                                       Almacafé
certification_address    e493c36c2d076bf273064f7ac23ad562af257a25
certification_contact    70d3c0c26f89e00fdae6fb39ff54f0d2eb1c38ab
unit_of_measurement                                             m
altitude_low_meters                                           NaN
altitude_high_meters                                          NaN
altitude_mean_meters                                          NaN
Name: 1197, dtype: object

In [78]:
# I also spotted some errors in two other names - Côte d'Ivoire, and "Tanzania, United Republic of" is a little bit bland.

country_replacements = {
    "Tanzania, United Republic Of": "Tanzania",
    "Cote d?Ivoire": "Côte d'Ivoire"
}

coffee_data["country_of_origin"] = coffee_data['country_of_origin'].replace(country_replacements)

In [79]:
coffee_data["country_of_origin"].value_counts(dropna = False)

country_of_origin
Mexico                         236
Colombia                       184
Guatemala                      181
Brazil                         132
Taiwan                          75
United States (Hawaii)          73
Honduras                        53
Costa Rica                      51
Ethiopia                        44
Tanzania                        40
Uganda                          36
Thailand                        32
Nicaragua                       26
Kenya                           25
El Salvador                     21
Indonesia                       20
China                           16
India                           14
Malawi                          11
Peru                            10
United States                   10
Vietnam                          8
Myanmar                          8
Haiti                            6
Philippines                      5
Panama                           4
United States (Puerto Rico)      4
Ecuador                          3
Laos                             3
Burundi                          2
Papua New Guinea                 1
Japan                            1
Zambia                           1
Rwanda                           1
Mauritius                        1
Côte d'Ivoire                    1
Name: count, dtype: int64

In [82]:
# Now I move on to the next column which is farm_name
coffee_data["farm_name"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1339 entries, 0 to 1338
Series name: farm_name
Non-Null Count  Dtype
--------------  -----
980 non-null    object
dtypes: object(1)
memory usage: 10.6+ KB

In [102]:
# There are 359 NaN values in the "farm_name" column.
# That is why I will replace with "Unspecified"
1339 - 980

359

In [98]:
coffee_data["farm_name"] = coffee_data["farm_name"].fillna("Unspecified")

In [101]:
(coffee_data["farm_name"] == "Unspecified").value_counts()

farm_name
False    980
True     359
Name: count, dtype: int64

In [103]:
coffee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1339 entries, 0 to 1338
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   species                1339 non-null   category
 1   owner                  1339 non-null   object
 2   country_of_origin      1339 non-null   object
 3   farm_name              1339 non-null   object
 4   lot_number             276 non-null    object
 5   mill                   1021 non-null   object
 6   ico_number             1180 non-null   object
 7   company                1130 non-null   object
 8   altitude               1113 non-null   object
 9   region                 1280 non-null   object
 10  producer               1107 non-null   object
 11  number_of_bags         1339 non-null   int64
 12  bag_weight             1339 non-null   object
 13  in_country_partner     1339 non-null   object
 14  harvest_year           1292 non-null   object
 15  grading_date           1339 non-null   object
 16  owner_1                1332 non-null   object
 17  variety                1113 non-null   object
 18  processing_method      1169 non-null   object
 19  aroma                  1339 non-null   float64
 20  flavor                 1339 non-null   float64
 21  aftertaste             1339 non-null   float64
 22  acidity                1339 non-null   float64
 23  body                   1339 non-null   float64
 24  balance                1339 non-null   float64
 25  uniformity             1339 non-null   float64
 26  clean_cup              1339 non-null   float64
 27  sweetness              1339 non-null   float64
 28  cupper_points          1339 non-null   float64
 29  total_cup_points       1339 non-null   float64
 30  moisture               1339 non-null   float64
 31  category_one_defects   1339 non-null   int64
 32  quakers                1338 non-null   float64
 33  color                  1069 non-null   object
 34  category_two_defects   1339 non-null   int64
 35  expiration             1339 non-null   object
 36  certification_body     1339 non-null   object
 37  certification_address  1339 non-null   object
 38  certification_contact  1339 non-null   object
 39  unit_of_measurement    1339 non-null   object
 40  altitude_low_meters    1109 non-null   float64
 41  altitude_high_meters   1109 non-null   float64
 42  altitude_mean_meters   1109 non-null   float64
dtypes: category(1), float64(16), int64(3), object(23)
memory usage: 440.9+ KB

In [106]:
# The lot_number has only 276 not Nan values which means that it is not a vital variable for analysis.
# That is why I think it will be better to remove it
coffee_data["lot_number"].value_counts(dropna = False)

lot_number
NaN         1063
1             18
020/17         6
019/17         5
2              3
            ...
7              1
RKR            1
RC AB          1
Lavado 1       1
Lavado 3       1
Name: count, Length: 228, dtype: int64

In [108]:
coffee_data["lot_number"].nunique()

227

In [114]:
coffee_data['lot_number'].notna().sum() / len(coffee_data) * 100

np.float64(20.612397311426438)