In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Data Tidying and Cleaning Demos 3
## Live Demos

In [3]:
weather_data = pd.read_csv("02.Data-Tidying-and-Cleaning-Materials/weather.csv")

In [4]:
weather_data

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
weather_data.id.value_counts()

id
MX17004    22
Name: count, dtype: int64

In [6]:
weather_data.month

0      1
1      1
2      2
3      2
4      3
5      3
6      4
7      4
8      5
9      5
10     6
11     6
12     7
13     7
14     8
15     8
16    10
17    10
18    11
19    11
20    12
21    12
Name: month, dtype: int64

In [7]:
weather_data = weather_data.melt(id_vars = ["id", "year", "month", "element"])

In [8]:
weather_data

          id  year  month element variable  value
0    MX17004  2010      1    tmax       d1    NaN
1    MX17004  2010      1    tmin       d1    NaN
2    MX17004  2010      2    tmax       d1    NaN
3    MX17004  2010      2    tmin       d1    NaN
4    MX17004  2010      3    tmax       d1    NaN
..       ...   ...    ...     ...      ...    ...
677  MX17004  2010     10    tmin      d31    NaN
678  MX17004  2010     11    tmax      d31    NaN
679  MX17004  2010     11    tmin      d31    NaN
680  MX17004  2010     12    tmax      d31    NaN
681  MX17004  2010     12    tmin      d31    NaN

[682 rows x 6 columns]

In [9]:
weather_data.value.unique()

array([ nan, 29.9, 13.8, 27.3, 14.4, 31.3, 16.3, 24.1, 28.6, 17.5, 27.2,
       12. , 32.1, 14.2, 29.6, 15.8, 27. , 14. , 26.3,  7.9, 27.8, 10.5,
       28.1, 12.9, 29. , 17.3, 34.5, 16.8, 29.7, 13.4, 29.8, 16.5, 29.5,
       13. , 28.7, 31.1, 17.6, 28. , 10.7, 26.4, 15. , 15.6, 12.1, 36.3,
       16.7, 33.2, 18.2, 27.7, 31.2, 30.1, 18. , 15.3, 14.5, 25.4, 15.4])

In [10]:
weather_data.pivot_table(index = ["id", "year", "month", "variable", "value"], columns = ["element"])

Empty DataFrame
Columns: []
Index: [(MX17004, 2010, 1, d30, 14.5), (MX17004, 2010, 1, d30, 27.8), (MX17004, 2010, 2, d11, 13.4), (MX17004, 2010, 2, d11, 29.7), (MX17004, 2010, 2, d2, 14.4), (MX17004, 2010, 2, d2, 27.3), (MX17004, 2010, 2, d23, 10.7), (MX17004, 2010, 2, d23, 29.9), (MX17004, 2010, 2, d3, 14.4), (MX17004, 2010, 2, d3, 24.1), (MX17004, 2010, 3, d10, 16.8), (MX17004, 2010, 3, d10, 34.5), (MX17004, 2010, 3, d16, 17.6), (MX17004, 2010, 3, d16, 31.1), (MX17004, 2010, 3, d5, 14.2), (MX17004, 2010, 3, d5, 32.1), (MX17004, 2010, 4, d27, 16.7), (MX17004, 2010, 4, d27, 36.3), (MX17004, 2010, 5, d27, 18.2), (MX17004, 2010, 5, d27, 33.2), (MX17004, 2010, 6, d17, 17.5), (MX17004, 2010, 6, d17, 28.0), (MX17004, 2010, 6, d29, 18.0), (MX17004, 2010, 6, d29, 30.1), (MX17004, 2010, 7, d3, 17.5), (MX17004, 2010, 7, d3, 28.6), (MX17004, 2010, 7, d14, 16.5), (MX17004, 2010, 7, d14, 29.9), (MX17004, 2010, 8, d23, 15.0), (MX17004, 2010, 8, d23, 26.4), (MX17004, 2010, 8, d5, 15.8), (MX17004, 2010, 8, d5, 29.6), (MX17004, 2010, 8, d29, 15.3), (MX17004, 2010, 8, d29, 28.0), (MX17004, 2010, 8, d13, 16.5), (MX17004, 2010, 8, d13, 29.8), (MX17004, 2010, 8, d25, 15.6), (MX17004, 2010, 8, d25, 29.7), (MX17004, 2010, 8, d31, 15.4), (MX17004, 2010, 8, d31, 25.4), (MX17004, 2010, 8, d8, 17.3), (MX17004, 2010, 8, d8, 29.0), (MX17004, 2010, 10, d5, 14.0), (MX17004, 2010, 10, d5, 27.0), (MX17004, 2010, 10, d14, 13.0), (MX17004, 2010, 10, d14, 29.5), (MX17004, 2010, 10, d15, 10.5), (MX17004, 2010, 10, d15, 28.7), (MX17004, 2010, 10, d28, 15.0), (MX17004, 2010, 10, d28, 31.2), (MX17004, 2010, 10, d7, 12.9), (MX17004, 2010, 10, d7, 28.1), (MX17004, 2010, 11, d2, 16.3), (MX17004, 2010, 11, d2, 31.3), (MX17004, 2010, 11, d5, 7.9), (MX17004, 2010, 11, d5, 26.3), (MX17004, 2010, 11, d27, 14.2), (MX17004, 2010, 11, d27, 27.7), (MX17004, 2010, 11, d26, 12.1), (MX17004, 2010, 11, d26, 28.1), (MX17004, 2010, 11, d4, 12.0), (MX17004, 2010, 11, d4, 27.2), (MX17004, 2010, 12, d1, 13.8), (MX17004, 2010, 12, d1, 29.9), (MX17004, 2010, 12, d6, 10.5), (MX17004, 2010, 12, d6, 27.8)]

[66 rows x 0 columns]

In [11]:
weather_data.variable.str.slice(1)

0       1
1       1
2       1
3       1
4       1
       ..
677    31
678    31
679    31
680    31
681    31
Name: variable, Length: 682, dtype: object

In [20]:
weather_data.variable.str.slice(1).astype(int)

0       1
1       1
2       1
3       1
4       1
       ..
677    31
678    31
679    31
680    31
681    31
Name: variable, Length: 682, dtype: int64

In [18]:
weather_data.pivot_table(index = ["id", "year", "month", "variable", "value"], columns = ["element"]).reset_index()

              id  year month variable value
element
0        MX17004  2010     1      d30  14.5
1        MX17004  2010     1      d30  27.8
2        MX17004  2010     2      d11  13.4
3        MX17004  2010     2      d11  29.7
4        MX17004  2010     2       d2  14.4
..           ...   ...   ...      ...   ...
61       MX17004  2010    11       d4  27.2
62       MX17004  2010    12       d1  13.8
63       MX17004  2010    12       d1  29.9
64       MX17004  2010    12       d6  10.5
65       MX17004  2010    12       d6  27.8

[66 rows x 5 columns]

In [12]:
weather_data.variable = weather_data.variable.str.slice(1).astype(int)

In [13]:
weather_data.variable

0       1
1       1
2       1
3       1
4       1
       ..
677    31
678    31
679    31
680    31
681    31
Name: variable, Length: 682, dtype: int64

In [14]:
weather_data[["year", "month", "variable"]]

     year  month  variable
0    2010      1         1
1    2010      1         1
2    2010      2         1
3    2010      2         1
4    2010      3         1
..    ...    ...       ...
677  2010     10        31
678  2010     11        31
679  2010     11        31
680  2010     12        31
681  2010     12        31

[682 rows x 3 columns]

In [15]:
pd.to_datetime(weather_data[["year", "month", "variable"]])

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day] is missing

In [20]:
weather_data.day = weather_data.variable

In [19]:
pd.to_datetime(weather_data[["year", "month", "day"]])

KeyError: "['day'] not in index"

In [21]:
weather_data.day = weather_data.variable

In [22]:
pd.to_datetime(weather_data[["year", "month", "day"]])

KeyError: "['day'] not in index"

In [5]:
weather_data = weather_data.melt(id_vars = ["id", "year", "month", "element"], var_name = "day")

In [6]:
weather_data

          id  year  month element  day  value
0    MX17004  2010      1    tmax   d1    NaN
1    MX17004  2010      1    tmin   d1    NaN
2    MX17004  2010      2    tmax   d1    NaN
3    MX17004  2010      2    tmin   d1    NaN
4    MX17004  2010      3    tmax   d1    NaN
..       ...   ...    ...     ...  ...    ...
677  MX17004  2010     10    tmin  d31    NaN
678  MX17004  2010     11    tmax  d31    NaN
679  MX17004  2010     11    tmin  d31    NaN
680  MX17004  2010     12    tmax  d31    NaN
681  MX17004  2010     12    tmin  d31    NaN

[682 rows x 6 columns]

In [7]:
weather_data = weather_data.rename(columns = {"variable": "day"})

In [9]:
weather_data.day.value_counts()

day
d1     22
d2     22
d3     22
d4     22
d5     22
d6     22
d7     22
d8     22
d9     22
d10    22
d11    22
d12    22
d13    22
d14    22
d15    22
d16    22
d17    22
d18    22
d19    22
d20    22
d21    22
d22    22
d23    22
d24    22
d25    22
d26    22
d27    22
d28    22
d29    22
d30    22
d31    22
Name: count, dtype: int64

In [7]:
weather_data.day = weather_data.day.str.slice(1).astype(int)

In [8]:
weather_data.dtypes

id          object
year         int64
month        int64
element     object
day          int64
value      float64
dtype: object

In [12]:
weather_data[
    (weather_data.month == 6) &
    (weather_data.day == 31)
]

          id  year  month element  day  value
670  MX17004  2010      6    tmax   31    NaN
671  MX17004  2010      6    tmin   31    NaN

In [19]:
weather_data = weather_data.dropna()

In [20]:
weather_data

          id  year  month element  day  value
20   MX17004  2010     12    tmax    1   29.9
21   MX17004  2010     12    tmin    1   13.8
24   MX17004  2010      2    tmax    2   27.3
25   MX17004  2010      2    tmin    2   14.4
40   MX17004  2010     11    tmax    2   31.3
..       ...   ...    ...     ...  ...    ...
631  MX17004  2010      8    tmin   29   15.3
638  MX17004  2010      1    tmax   30   27.8
639  MX17004  2010      1    tmin   30   14.5
674  MX17004  2010      8    tmax   31   25.4
675  MX17004  2010      8    tmin   31   15.4

[66 rows x 6 columns]

In [22]:
weather_data[["year", "month", "day"]]

     year  month  day
20   2010     12    1
21   2010     12    1
24   2010      2    2
25   2010      2    2
40   2010     11    2
..    ...    ...  ...
631  2010      8   29
638  2010      1   30
639  2010      1   30
674  2010      8   31
675  2010      8   31

[66 rows x 3 columns]

In [24]:
weather_data["date"] = pd.to_datetime(weather_data[["year", "month", "day"]])

In [25]:
weather_data

          id  year  month element  day  value       date
20   MX17004  2010     12    tmax    1   29.9 2010-12-01
21   MX17004  2010     12    tmin    1   13.8 2010-12-01
24   MX17004  2010      2    tmax    2   27.3 2010-02-02
25   MX17004  2010      2    tmin    2   14.4 2010-02-02
40   MX17004  2010     11    tmax    2   31.3 2010-11-02
..       ...   ...    ...     ...  ...    ...        ...
631  MX17004  2010      8    tmin   29   15.3 2010-08-29
638  MX17004  2010      1    tmax   30   27.8 2010-01-30
639  MX17004  2010      1    tmin   30   14.5 2010-01-30
674  MX17004  2010      8    tmax   31   25.4 2010-08-31
675  MX17004  2010      8    tmin   31   15.4 2010-08-31

[66 rows x 7 columns]

In [27]:
weather_data = weather_data.drop(columns = ["year", "month", "day"])

In [28]:
weather_data

          id element  value       date
20   MX17004    tmax   29.9 2010-12-01
21   MX17004    tmin   13.8 2010-12-01
24   MX17004    tmax   27.3 2010-02-02
25   MX17004    tmin   14.4 2010-02-02
40   MX17004    tmax   31.3 2010-11-02
..       ...     ...    ...        ...
631  MX17004    tmin   15.3 2010-08-29
638  MX17004    tmax   27.8 2010-01-30
639  MX17004    tmin   14.5 2010-01-30
674  MX17004    tmax   25.4 2010-08-31
675  MX17004    tmin   15.4 2010-08-31

[66 rows x 4 columns]

In [32]:
plt.plot(weather_data.date, weather_data.value)

In [34]:
weather_data.pivot_table(index = ["id", "date"], columns = ["element"])

                   value
element             tmax  tmin
id      date
MX17004 2010-01-30  27.8  14.5
        2010-02-02  27.3  14.4
        2010-02-03  24.1  14.4
        2010-02-11  29.7  13.4
        2010-02-23  29.9  10.7
        2010-03-05  32.1  14.2
        2010-03-10  34.5  16.8
        2010-03-16  31.1  17.6
        2010-04-27  36.3  16.7
        2010-05-27  33.2  18.2
        2010-06-17  28.0  17.5
        2010-06-29  30.1  18.0
        2010-07-03  28.6  17.5
        2010-07-14  29.9  16.5
        2010-08-05  29.6  15.8
        2010-08-08  29.0  17.3
        2010-08-13  29.8  16.5
        2010-08-23  26.4  15.0
        2010-08-25  29.7  15.6
        2010-08-29  28.0  15.3
        2010-08-31  25.4  15.4
        2010-10-05  27.0  14.0
        2010-10-07  28.1  12.9
        2010-10-14  29.5  13.0
        2010-10-15  28.7  10.5
        2010-10-28  31.2  15.0
        2010-11-02  31.3  16.3
        2010-11-04  27.2  12.0
        2010-11-05  26.3   7.9
        2010-11-26  28.1  12.1
        2010-11-27  27.7  14.2
        2010-12-01  29.9  13.8
        2010-12-06  27.8  10.5

In [36]:
weather_data = weather_data.pivot_table(index = ["id", "date"], columns = ["element"]).reset_index()

In [37]:
weather_data

              id       date value
element                      tmax  tmin
0        MX17004 2010-01-30  27.8  14.5
1        MX17004 2010-02-02  27.3  14.4
2        MX17004 2010-02-03  24.1  14.4
3        MX17004 2010-02-11  29.7  13.4
4        MX17004 2010-02-23  29.9  10.7
5        MX17004 2010-03-05  32.1  14.2
6        MX17004 2010-03-10  34.5  16.8
7        MX17004 2010-03-16  31.1  17.6
8        MX17004 2010-04-27  36.3  16.7
9        MX17004 2010-05-27  33.2  18.2
10       MX17004 2010-06-17  28.0  17.5
11       MX17004 2010-06-29  30.1  18.0
12       MX17004 2010-07-03  28.6  17.5
13       MX17004 2010-07-14  29.9  16.5
14       MX17004 2010-08-05  29.6  15.8
15       MX17004 2010-08-08  29.0  17.3
16       MX17004 2010-08-13  29.8  16.5
17       MX17004 2010-08-23  26.4  15.0
18       MX17004 2010-08-25  29.7  15.6
19       MX17004 2010-08-29  28.0  15.3
20       MX17004 2010-08-31  25.4  15.4
21       MX17004 2010-10-05  27.0  14.0
22       MX17004 2010-10-07  28.1  12.9
23       MX17004 2010-10-14  29.5  13.0
24       MX17004 2010-10-15  28.7  10.5
25       MX17004 2010-10-28  31.2  15.0
26       MX17004 2010-11-02  31.3  16.3
27       MX17004 2010-11-04  27.2  12.0
28       MX17004 2010-11-05  26.3   7.9
29       MX17004 2010-11-26  28.1  12.1
30       MX17004 2010-11-27  27.7  14.2
31       MX17004 2010-12-01  29.9  13.8
32       MX17004 2010-12-06  27.8  10.5

In [38]:
plt.plot(weather_data.date, weather_data.value)

[<matplotlib.lines.Line2D at 0x277948db750>,
 <matplotlib.lines.Line2D at 0x277948db4d0>]