In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# COVID-19 DATASET ANALYSIS

**The dataset was provided by the Mexican government. This dataset contains an enormous number of anonymized patient-related information including pre-conditions.**

The dataset is taken from Kaggle: https://www.kaggle.com/datasets/meirnizri/covid19-dataset

In [3]:
# Read the dataset
covid_data = pd.read_csv("data/covid_data.csv")
covid_data

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,...,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,...,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,...,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,...,2,2,2,2,2,2,2,2,7,97

In [4]:
# See the size of the dataset. 
# It has 1 048 575 observations (rows) and 21 features (columns).
# According to the data card in Kaggle it has one observation more but I suppose that the header was counted as an observation, too.
covid_data.shape

(1048575, 21)

**SIZE: 
1 048 575 rows & 21 columns**

In [5]:
# This helps me see all columns on my screen
pd.set_option('display.max_columns', 21)

In [6]:
covid_data

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,2,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,2,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,2,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,2,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,2,2,2,1,2,2,2,2,2,3,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2,13,2,1,9999-99-99,97,2,40,97,2,2,2,2,2,2,2,2,2,2,7,97
1048571,1,13,2,2,9999-99-99,2,2,51,97,2,2,2,2,1,2,2,2,2,2,7,2
1048572,2,13,2,1,9999-99-99,97,2,55,97,2,2,2,2,2,2,2,2,2,2,7,97
1048573,2,13,2,1,9999-99-99,97,2,28,97,2,2,2,2,2,2,2,2,2,2,7,97
1048574,2,13,2,1,9999-99-99,97,2,52,97,2,2,2,2,2,2,2,2,2,2,7,97

### Columns - types and meanings

In [7]:
covid_data.columns

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU'],
      dtype='object')

In [8]:
# I will make them in a more Pythonic style
covid_data.columns = covid_data.columns.str.lower()

In [9]:
covid_data.columns

Index(['usmer', 'medical_unit', 'sex', 'patient_type', 'date_died', 'intubed',
       'pneumonia', 'age', 'pregnant', 'diabetes', 'copd', 'asthma', 'inmsupr',
       'hipertension', 'other_disease', 'cardiovascular', 'obesity',
       'renal_chronic', 'tobacco', 'clasiffication_final', 'icu'],
      dtype='object')

###### In my opinion, the variables are not sorted well so I will sort them in a more human-friendly way.

In [10]:
new_order = [
    'sex', 'age', 'clasiffication_final',
    'patient_type', 'icu', 'intubed',
    'pneumonia', 'pregnant', 'diabetes', 'copd', 'asthma', 'inmsupr', 'hipertension',
    'cardiovascular', 'renal_chronic', 'other_disease', 'obesity', 'tobacco',
    'usmer', 'medical_unit', 'date_died'
]

covid_data = covid_data[new_order]

In [11]:
covid_data.columns

Index(['sex', 'age', 'clasiffication_final', 'patient_type', 'icu', 'intubed',
       'pneumonia', 'pregnant', 'diabetes', 'copd', 'asthma', 'inmsupr',
       'hipertension', 'cardiovascular', 'renal_chronic', 'other_disease',
       'obesity', 'tobacco', 'usmer', 'medical_unit', 'date_died'],
      dtype='object')

In [12]:
# Some of the columns have spelling errors so I fix them in a fast manual way.
covid_data = covid_data.rename(columns = {"clasiffication_final": "classification_final"})
covid_data = covid_data.rename(columns = {"hipertension": "hypertension"})

In [13]:
covid_data.columns

Index(['sex', 'age', 'classification_final', 'patient_type', 'icu', 'intubed',
       'pneumonia', 'pregnant', 'diabetes', 'copd', 'asthma', 'inmsupr',
       'hypertension', 'cardiovascular', 'renal_chronic', 'other_disease',
       'obesity', 'tobacco', 'usmer', 'medical_unit', 'date_died'],
      dtype='object')

#### Features Types

In [14]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   sex                   1048575 non-null  int64
 1   age                   1048575 non-null  int64
 2   classification_final  1048575 non-null  int64
 3   patient_type          1048575 non-null  int64
 4   icu                   1048575 non-null  int64
 5   intubed               1048575 non-null  int64
 6   pneumonia             1048575 non-null  int64
 7   pregnant              1048575 non-null  int64
 8   diabetes              1048575 non-null  int64
 9   copd                  1048575 non-null  int64
 10  asthma                1048575 non-null  int64
 11  inmsupr               1048575 non-null  int64
 12  hypertension          1048575 non-null  int64
 13  cardiovascular        1048575 non-null  int64
 14  renal_chronic         1048575 non-null  int64
 15  other_disease         1048575 non-null  int64
 16  obesity               1048575 non-null  int64
 17  tobacco               1048575 non-null  int64
 18  usmer                 1048575 non-null  int64
 19  medical_unit          1048575 non-null  int64
 20  date_died             1048575 non-null  object
dtypes: int64(20), object(1)
memory usage: 168.0+ MB

Correction of the data types can be done here.
There are no NaN values. According to the dataset description in Kaggle: if there is an observation with an unmeasured feature, it is filled with a value. 
- From Kaggle desription: In the Boolean features, 1 means "yes" and 2 means "no". values as 97 and 99 are missing data.

#### Variable Optimization

Now let's look at the variables one by one and see what can be done for optimization

##### Sex

In [15]:
# See the unique values for the sex.
covid_data.sex.unique()

array([1, 2])

In [16]:
# As there are only two values, sex is a categorical variable but it is recorded as int.
# Solution for optimization: 1.Convert 'sex' to type "category". 2. For better understanding I will use f (from female) instead of 1 and m (from male) instead of 2
covid_data.sex = covid_data.sex.astype("category")
covid_data.sex = covid_data.sex.replace({1: "f", 2: "m"})

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\3185442190.py:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data.sex = covid_data.sex.replace({1: "f", 2: "m"})

In [17]:
covid_data

,sex,age,classification_final,patient_type,icu,intubed,pneumonia,pregnant,diabetes,copd,asthma,inmsupr,hypertension,cardiovascular,renal_chronic,other_disease,obesity,tobacco,usmer,medical_unit,date_died
0,f,65,3,1,97,97,1,2,2,2,2,2,1,2,2,2,2,2,2,1,03/05/2020
1,m,72,5,1,97,97,1,97,2,2,2,2,1,2,1,2,1,2,2,1,03/06/2020
2,m,55,3,2,2,1,2,97,1,2,2,2,2,2,2,2,2,2,2,1,09/06/2020
3,f,53,7,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,1,12/06/2020
4,m,68,3,1,97,97,2,97,1,2,2,2,1,2,2,2,2,2,2,1,21/06/2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,m,40,7,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,13,9999-99-99
1048571,m,51,7,2,2,2,2,97,2,2,2,2,1,2,2,2,2,2,1,13,9999-99-99
1048572,m,55,7,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,13,9999-99-99
1048573,m,28,7,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,13,9999-99-99
1048574,m,52,7,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,13,9999-99-99

##### Age

In [18]:
# A quick check if everything with the variable 'age' is fine.
# First, I look for invalid values such as -50 using the unique() method
covid_data.age.unique()

array([ 65,  72,  55,  53,  68,  40,  64,  37,  25,  38,  24,  30,  48,
        23,  80,  61,  54,  59,  45,  26,  32,  49,  39,  27,  57,  20,
        56,  47,  50,  46,  43,  28,  33,  16,  62,  58,  36,  44,  66,
        52,  51,  35,  19,  90,  34,  22,  29,  14,  31,  42,  15,   1,
         0,  17,  41,   2,  10,  12,  13,   4,   7,   6,   8,  60,   5,
        63,  75,  81,  67,  18,  70,  88,  85,  92,  73,  74,  78,  76,
        82,  77,  86,  71,  95,  87,  83,  84,  79,  69,  89,   3,  97,
        93, 100,  91,  21, 103,  11,   9,  94,  96, 101, 107, 102,  98,
        99, 109, 119, 116, 105, 104, 111, 114, 120, 106, 108, 110, 118,
       117, 121, 115, 113])

In [19]:
# Accoring to my eye sight, there are not invalid ages but if this was a longer list, my sight would not be enough so automation of the process will be needed.
# I will take 125 years as the maximum life expectancy ---> source: https://en.wikipedia.org/wiki/Life_expectancy
if ((covid_data.age < 0) | (covid_data.age > 125)).any():
    print("There are invalid values.")
else:
    print("Everything is fine.")

Everything is fine.

In [20]:
covid_data.age.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1048575 entries, 0 to 1048574
Series name: age
Non-Null Count    Dtype
--------------    -----
1048575 non-null  int64
dtypes: int64(1)
memory usage: 8.0 MB

The variable type is int as it should. In conclusion, everything is fine with the column 'age'.

##### Classification_final

Meaning: 
    covid test findings. Values 1-3 mean that the patient was diagnosed with covid in different
    degrees. 4 or higher means that the patient is not a carrier of covid or that the test is inconclusive.

In [21]:
# Explore values
# According to the description of the feature in Kaggle the range of possible values is: [1; 3] --> covid  |   [4; +∞] --> not covid / unconvincing test
covid_data["classification_final"].unique()

array([3, 5, 7, 6, 1, 2, 4])

Values 1 to 3: Indicate that the patient is diagnosed with COVID-19. The lower the value, the more severe or advanced the infection:
- 1 = Highest degree of infection (most severe case)
- 2 = Moderate degree of infection
- 3 = Mild degree of infection

Values 4 or higher: Indicate that the patient is either not infected with COVID-19 or that the test result is inconclusive.

For machine learning models, numerical values are preferred for categorical variables. However, for the purpose of this analysis, it is better to replace these numbers with descriptive words since the numeric values alone are not very meaningful.

In [22]:
def replace_number(number):
    if number == 1:
        return "Severe COVID"
    elif number == 2:
        return "Moderate COVID"
    elif number == 3:
        return "Mild COVID"
    elif number >= 4:
        return "No COVID / Inconclusive"
    else:
        return "Invalid value"

covid_data["classification_final"] = [replace_number(num) for num in covid_data["classification_final"]]

In [23]:
covid_data["classification_final"].value_counts(dropna = False, normalize = True)

classification_final
No COVID / Inconclusive    0.626179
Mild COVID                 0.363853
Severe COVID               0.008203
Moderate COVID             0.001765
Name: proportion, dtype: float64

Approx. 63% of the people are not ill from COVID or at least their diagnosis is not clear.

In [24]:
covid_data[covid_data["classification_final"] == "No COVID / Inconclusive"].sample(20)

,sex,age,classification_final,patient_type,icu,intubed,pneumonia,pregnant,diabetes,copd,asthma,inmsupr,hypertension,cardiovascular,renal_chronic,other_disease,obesity,tobacco,usmer,medical_unit,date_died
1041046,m,34,No COVID / Inconclusive,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
874690,f,50,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
1044942,m,33,No COVID / Inconclusive,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
765665,f,7,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,1,12,9999-99-99
284162,f,35,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,1,4,9999-99-99
269826,f,34,No COVID / Inconclusive,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,4,9999-99-99
820634,f,60,No COVID / Inconclusive,2,2,2,2,2,1,2,2,2,1,2,2,2,2,2,1,12,9999-99-99
801574,f,17,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
381369,f,69,No COVID / Inconclusive,2,1,2,1,2,2,2,2,2,1,2,2,2,2,2,2,6,9999-99-99
1027673,m,46,No COVID / Inconclusive,1,97,97,2,97,2,2,2,2,2,2,2,2,1,2,1,12,9999-99-99
732794,m,7,No COVID / Inconclusive,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
665571,m,42,No COVID / Inconclusive,1,97,97,2,97,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
970713,m,71,No COVID / Inconclusive,1,97,97,1,97,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
255690,f,32,No COVID / Inconclusive,1,97,97,2,1,2,2,2,2,2,2,2,2,2,2,1,4,9999-99-99
726417,m,3,No COVID / Inconclusive,2,99,99,99,97,2,2,2,2,2,2,2,2,2,2,1,12,9999-99-99
421005,m,79,No COVID / Inconclusive,2,2,2,1,97,2,1,2,2,2,2,2,2,2,1,2,9,9999-99-99
194759,f,26,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,4,9999-99-99
686228,f,56,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99
827397,f,38,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,1,1,2,12,9999-99-99
1040119,f,40,No COVID / Inconclusive,1,97,97,2,2,2,2,2,2,2,2,2,2,2,2,2,12,9999-99-99

And because I will need only those who are COVID cases for my analysis, I will drop all the rows which have unclear diagnosis.

In [25]:
covid_data = covid_data.drop(covid_data[covid_data["classification_final"] == "No COVID / Inconclusive"].index)

In [26]:
covid_data.shape

(391979, 21)

In [27]:
covid_data["classification_final"].dtypes

dtype('O')

In [28]:
# The type of the variable 'classification_final' is object now because words were added.
# However, for memory optimization, the type "category" is prefered.

covid_data["classification_final"] = covid_data["classification_final"].astype("category")

##### Patient_Type

Meaning: type of care the patient received in the unit. 1 for returned home and 2 for hospitalization.

In [29]:
# A quick check of the values
covid_data["patient_type"].value_counts(dropna = False)

patient_type
1    280687
2    111292
Name: count, dtype: int64

In [30]:
# What can be noticed now is that 'patient_type' is also a categorical variable, and it fits the description given on Kaggle.
# Instead of int, 'patient_type' should be of type 'category'.
# I replace the numerical values, as I did with 'classification_final', because words are more meaningful for data analysis.
covid_data["patient_type"] = covid_data["patient_type"].astype("category")
covid_data["patient_type"] = covid_data["patient_type"].replace({1: "Sent home", 2: "Hospitalized"})

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\1169063600.py:5: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data["patient_type"] = covid_data["patient_type"].replace({1: "Sent home", 2: "Hospitalized"})

In [31]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391979 entries, 0 to 1047937
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   sex                   391979 non-null  category
 1   age                   391979 non-null  int64
 2   classification_final  391979 non-null  category
 3   patient_type          391979 non-null  category
 4   icu                   391979 non-null  int64
 5   intubed               391979 non-null  int64
 6   pneumonia             391979 non-null  int64
 7   pregnant              391979 non-null  int64
 8   diabetes              391979 non-null  int64
 9   copd                  391979 non-null  int64
 10  asthma                391979 non-null  int64
 11  inmsupr               391979 non-null  int64
 12  hypertension          391979 non-null  int64
 13  cardiovascular        391979 non-null  int64
 14  renal_chronic         391979 non-null  int64
 15  other_disease         391979 non-null  int64
 16  obesity               391979 non-null  int64
 17  tobacco               391979 non-null  int64
 18  usmer                 391979 non-null  int64
 19  medical_unit          391979 non-null  int64
 20  date_died             391979 non-null  object
dtypes: category(3), int64(17), object(1)
memory usage: 57.9+ MB

##### ICU (Intensive Care Unit)

Meaning: Indicates whether the patient had been admitted to an Intensive Care Unit.

In [32]:
# Check values
covid_data.icu.value_counts(dropna = False)

icu
97    280687
2      99322
1      10449
99      1521
Name: count, dtype: int64

In [33]:
# In the description in Kaggle this is mentioned: In the Boolean features, 1 means "yes" and 2 means "no". values as 97 and 99 are missing data.
# Check the type of 'icu'
covid_data.icu.dtype

dtype('int64')

ICU status is not recorded as a boolean feature. Nevertheless, based on the description provided on Kaggle, icu can be treated as a boolean variable.

In [34]:
covid_data.dtypes

sex                     category
age                        int64
classification_final    category
patient_type            category
icu                        int64
intubed                    int64
pneumonia                  int64
pregnant                   int64
diabetes                   int64
copd                       int64
asthma                     int64
inmsupr                    int64
hypertension               int64
cardiovascular             int64
renal_chronic              int64
other_disease              int64
obesity                    int64
tobacco                    int64
usmer                      int64
medical_unit               int64
date_died                 object
dtype: object

There are no features recorded as boolean so this is a clue to search for the meaning of the variables rather than the type they belong to. If a variable can be treated as boolean, then I can convert it to boolean. Overall, this means that values 97 and 99 represent missing values for 'icu', 1 stands for "yes" (been in Intensive Unit Care) and 2 stands for "no" (Not been in Intensive Unit Care).

In [35]:
# Convert 'icu' to type "category"
covid_data.icu = covid_data.icu.astype("category")

In [36]:
# See which are the observations with missing values in 'icu' and what is the difference between missing value replaced with 97 and missing value replaced with 99
missing_values = covid_data[(covid_data.icu == 99)][["patient_type"]]
missing_values["patient_type"].value_counts(dropna = False)

patient_type
Hospitalized    1521
Sent home          0
Name: count, dtype: int64

In [37]:
missing_values1 = covid_data[(covid_data.icu == 97)][["patient_type"]]
missing_values1["patient_type"].value_counts(dropna = False)

patient_type
Sent home       280687
Hospitalized         0
Name: count, dtype: int64

Now the difference is visible: 99 represents patients who have been hospitalized but it is uncertain if they were admited to an ICU, while 97 represents patients who were sent home but ICU status is uncertain.
Summary: 
- 97 = Sent home, ICU status uncertain
- 99 = Hospitalized, ICU status uncertain

In [38]:
# I replace 97 and 99 with just one value for missing data, naming it "Unknown". The focus is only on the ICU status - yes, no or unknown;
# If information about the patient type is needed, the column "patient_type" can help so 97 and 99 are unnecessary for the analysis.

covid_data['icu'] = covid_data['icu'].cat.add_categories('Unknown')

covid_data['icu'] = covid_data['icu'].replace({
    1: 'Yes',
    2: 'No',
    97: 'Unknown',
    99: 'Unknown'
})

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\774514821.py:6: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data['icu'] = covid_data['icu'].replace({

In [39]:
covid_data.icu.value_counts(dropna = False)

icu
Unknown    282208
No          99322
Yes         10449
Name: count, dtype: int64

In [40]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391979 entries, 0 to 1047937
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   sex                   391979 non-null  category
 1   age                   391979 non-null  int64
 2   classification_final  391979 non-null  category
 3   patient_type          391979 non-null  category
 4   icu                   391979 non-null  category
 5   intubed               391979 non-null  int64
 6   pneumonia             391979 non-null  int64
 7   pregnant              391979 non-null  int64
 8   diabetes              391979 non-null  int64
 9   copd                  391979 non-null  int64
 10  asthma                391979 non-null  int64
 11  inmsupr               391979 non-null  int64
 12  hypertension          391979 non-null  int64
 13  cardiovascular        391979 non-null  int64
 14  renal_chronic         391979 non-null  int64
 15  other_disease         391979 non-null  int64
 16  obesity               391979 non-null  int64
 17  tobacco               391979 non-null  int64
 18  usmer                 391979 non-null  int64
 19  medical_unit          391979 non-null  int64
 20  date_died             391979 non-null  object
dtypes: category(4), int64(16), object(1)
memory usage: 55.3+ MB

##### Intubed

Meaning: whether the patient was connected to the ventilator.

In [41]:
# Check values of 'intubed'
covid_data.intubed.value_counts(dropna = False)

intubed
97    280687
2      86109
1      23670
99      1513
Name: count, dtype: int64

In [42]:
# 'Intubed' is meant to be a boolean variable, too. That is why, I proceed in the same way as I did with 'icu'.
# 1. Convert it to type "category". 
# 2. Add new category.
# 3. Replace {1, 2, 97, 99} with {Yes, No, Unknown}.

covid_data['intubed'] = covid_data['intubed'].astype("category")
covid_data['intubed'] = covid_data['intubed'].cat.add_categories('Unknown')

covid_data['intubed'] = covid_data['intubed'].replace({
    1: 'Yes',
    2: 'No',
    97: 'Unknown',
    99: 'Unknown'
})

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\2135586553.py:9: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data['intubed'] = covid_data['intubed'].replace({

##### Columns 6-18
- pneumonia: whether the patient already have air sacs inflammation or not.
- pregnancy: whether the patient is pregnant or not.
- diabetes: whether the patient has diabetes or not.
- copd: Indicates whether the patient has Chronic obstructive pulmonary disease or not.
- asthma: whether the patient has asthma or not.
- inmsupr: whether the patient is immunosuppressed or not.
- hypertension: whether the patient has hypertension or not.
- cardiovascular: whether the patient has heart or blood vessels related disease.
- renal chronic: whether the patient has chronic renal disease or not.
- other disease: whether the patient has other disease or not.
- obesity: whether the patient is obese or not.
- tobacco: whether the patient is a tobacco user.

Based on the description of the dataset in Kaggle, columns 6-18 represent boolean variables concerning medical conditions or illnesses, possessed by some patients. 
I explore all of these columns in an automatic way with a for loop because I suppose that all of them will need the same procedure as the the columns 'ico' and 'intubed'.

In [43]:
for col in covid_data.columns[6:18]:
    print(f"Value counts for {col}:")
    print(covid_data[col].value_counts(dropna=False))
    print("\n" + "-"*50 + "\n")

Value counts for pneumonia:
pneumonia
2     305934
1      86041
99         4
Name: count, dtype: int64

--------------------------------------------------

Value counts for pregnant:
pregnant
97    209489
2     178353
1       2754
98      1383
Name: count, dtype: int64

--------------------------------------------------

Value counts for diabetes:
diabetes
2     328425
1      62114
98      1440
Name: count, dtype: int64

--------------------------------------------------

Value counts for copd:
copd
2     384535
1       6131
98      1313
Name: count, dtype: int64

--------------------------------------------------

Value counts for asthma:
asthma
2     380258
1      10412
98      1309
Name: count, dtype: int64

--------------------------------------------------

Value counts for inmsupr:
inmsupr
2     385757
1       4773
98      1449
Name: count, dtype: int64

--------------------------------------------------

Value counts for hypertension:
hypertension
2     313864
1      76727
98      1388
Name: count, dtype: int64

--------------------------------------------------

Value counts for cardiovascular:
cardiovascular
2     382082
1       8506
98      1391
Name: count, dtype: int64

--------------------------------------------------

Value counts for renal_chronic:
renal_chronic
2     382677
1       7952
98      1350
Name: count, dtype: int64

--------------------------------------------------

Value counts for other_disease:
other_disease
2     379825
1      10018
98      2136
Name: count, dtype: int64

--------------------------------------------------

Value counts for obesity:
obesity
2     317852
1      72774
98      1353
Name: count, dtype: int64

--------------------------------------------------

Value counts for tobacco:
tobacco
2     361798
1      28747
98      1434
Name: count, dtype: int64

--------------------------------------------------

Based on the results, each of these features can be recorded as boolean and can acquire more descriptive value.

In [44]:
for col in covid_data.columns[6:18]:
    covid_data[col] = covid_data[col].astype("category")
    covid_data[col] = covid_data[col].cat.add_categories('Unknown')

    covid_data[col] = covid_data[col].replace({
        1: 'Yes',
        2: 'No',
        97: 'Unknown',
        99: 'Unknown'
    })

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\4147265796.py:5: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data[col] = covid_data[col].replace({

In [45]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391979 entries, 0 to 1047937
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   sex                   391979 non-null  category
 1   age                   391979 non-null  int64
 2   classification_final  391979 non-null  category
 3   patient_type          391979 non-null  category
 4   icu                   391979 non-null  category
 5   intubed               391979 non-null  category
 6   pneumonia             391979 non-null  category
 7   pregnant              391979 non-null  category
 8   diabetes              391979 non-null  category
 9   copd                  391979 non-null  category
 10  asthma                391979 non-null  category
 11  inmsupr               391979 non-null  category
 12  hypertension          391979 non-null  category
 13  cardiovascular        391979 non-null  category
 14  renal_chronic         391979 non-null  category
 15  other_disease         391979 non-null  category
 16  obesity               391979 non-null  category
 17  tobacco               391979 non-null  category
 18  usmer                 391979 non-null  int64
 19  medical_unit          391979 non-null  int64
 20  date_died             391979 non-null  object
dtypes: category(17), int64(3), object(1)
memory usage: 21.3+ MB

In [46]:
covid_data.sample(20)

,sex,age,classification_final,patient_type,icu,intubed,pneumonia,pregnant,diabetes,copd,asthma,inmsupr,hypertension,cardiovascular,renal_chronic,other_disease,obesity,tobacco,usmer,medical_unit,date_died
119082,f,50,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,Yes,Yes,No,No,Yes,No,2,4,9999-99-99
554529,m,51,Mild COVID,Sent home,Unknown,Unknown,No,Unknown,No,No,No,No,No,No,No,No,No,No,1,12,9999-99-99
351648,m,30,Mild COVID,Hospitalized,No,No,Yes,Unknown,No,No,No,No,No,No,No,No,No,No,1,6,9999-99-99
619865,f,48,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,Yes,No,Yes,No,No,No,2,12,9999-99-99
127607,f,27,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,No,No,2,4,9999-99-99
151492,f,47,Mild COVID,Hospitalized,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,2,4,9999-99-99
88121,f,49,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,Yes,No,2,4,9999-99-99
638924,f,57,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,Yes,No,No,No,No,No,2,12,9999-99-99
67431,f,45,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,No,No,1,4,9999-99-99
528021,f,26,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,Yes,No,2,12,9999-99-99
493160,f,50,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,No,Yes,2,12,9999-99-99
346419,f,44,Mild COVID,Hospitalized,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,1,6,18/07/2020
510434,f,43,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,No,No,No,No,No,No,2,12,9999-99-99
554631,m,35,Mild COVID,Sent home,Unknown,Unknown,No,Unknown,No,No,No,No,No,No,No,No,No,No,2,12,9999-99-99
354384,m,50,Mild COVID,Hospitalized,No,No,Yes,Unknown,Yes,No,No,No,No,No,No,No,No,No,2,6,9999-99-99
460167,m,58,Mild COVID,Hospitalized,Yes,Yes,Yes,Unknown,No,No,Yes,No,No,No,No,No,No,No,1,12,22/06/2020
568097,f,42,Mild COVID,Sent home,Unknown,Unknown,No,No,Yes,No,Yes,No,Yes,No,No,No,Yes,No,2,12,9999-99-99
633223,m,33,Mild COVID,Hospitalized,No,No,No,Unknown,No,No,No,No,No,No,No,No,Yes,No,1,12,9999-99-99
8912,f,53,Mild COVID,Sent home,Unknown,Unknown,No,No,No,No,No,No,Yes,No,No,No,No,No,1,3,9999-99-99
596980,f,41,Mild COVID,Sent home,Unknown,Unknown,No,No,Yes,No,Yes,No,No,No,No,No,No,No,1,12,9999-99-99

##### USMER

Meaning: USMER (Unidad de Salud Monitoras de Enfermedad Respiratoria / Viral Respiratory Disease Monitoring Health Unit)  
This indicates whether the patient treated medical units of the first, second, or third level. (Description on Kaggle, which is a little bit confusing) 

An explanation of the levels of healthcare in Mexico can be found here: https://www.internations.org/mexico-expats/guide/healthcare

- Free primary (e.g. General Practitioner or nurse) 
- Secondary (e.g. specialist doctor) healthcare. 
- Tertiary care (i.e. highly specialized treatments) is subject to fees.

Description of the feature after some research:
    Indicates whether the patient was treated in a sentinel surveillance health unit specialized in monitoring viral respiratory diseases (e.g., influenza, COVID-19). USMER units exist at all three levels of healthcare in Mexico:

- Value = 1 → Patient treated in a USMER unit (part of the national respiratory-disease surveillance network).
- Value = 2 → Patient treated in a non-USMER unit (outside the sentinel network).

In [47]:
covid_data.usmer.value_counts(dropna = False)

usmer
2    244853
1    147126
Name: count, dtype: int64

In [48]:
# The same procedures as the previous ones but this time there is no missing data.
covid_data.usmer = covid_data.usmer.astype("category")

covid_data.usmer = covid_data.usmer.replace({
        1: 'Yes',
        2: 'No',
})

C:\Users\aneli\AppData\Local\Temp\ipykernel_11964\2443293804.py:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  covid_data.usmer = covid_data.usmer.replace({

##### Medical Unit

Meaning: type of institution of the National Health System that provided the care.

In [49]:
# Check values
covid_data["medical_unit"].value_counts(dropna = False)

medical_unit
12    208226
4     126649
6      17688
9      14585
3       8631
8       4994
10      3807
11      3735
5       2853
7        414
13       345
1         40
2         12
Name: count, dtype: int64

In [50]:
# See the unique medical unit values sorted
covid_data["medical_unit"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Range [1-13]
However, there is no information on the different types of medical units used for the collection of the data.

In [51]:
# Convert to a type category
covid_data["medical_unit"] = covid_data["medical_unit"].astype("category")

##### Date Died

Meaning: If the patient died, indicate the date of death, and 9999-99-99 otherwise.

In [52]:
# Check for the type
covid_data["date_died"].info()

<class 'pandas.core.series.Series'>
Index: 391979 entries, 0 to 1047937
Series name: date_died
Non-Null Count   Dtype
--------------   -----
391979 non-null  object
dtypes: object(1)
memory usage: 6.0+ MB

In [53]:
covid_data["date_died"].value_counts()

date_died
9999-99-99    337743
13/07/2020       787
06/07/2020       773
16/07/2020       761
07/07/2020       758
               ...
22/10/2020         1
27/11/2020         1
25/11/2020         1
25/12/2020         1
03/12/2020         1
Name: count, Length: 288, dtype: int64

Something with the "9999-99-99" (representing that the patient is still alive) should be done so that the variable can become of type datetime because datetime accepts months and dates in the interval [1-12].
Solution: replace "9999-99-99" with NaN

In [54]:
covid_data["date_died"] = covid_data["date_died"].replace('9999-99-99', np.nan)

# Convert to datetime
covid_data["date_died"] = pd.to_datetime(covid_data["date_died"], format = "mixed")

In [55]:
covid_data["date_died"].value_counts(dropna = False)

date_died
NaT           337743
2020-07-13       787
2020-06-07       773
2020-07-16       761
2020-07-07       758
               ...
2020-10-22         1
2020-11-27         1
2020-11-25         1
2020-12-25         1
2020-03-12         1
Name: count, Length: 288, dtype: int64

#### Summary of the process up-to-now

**What I did up-to-now:**
1. Renamed the columns so that they use snake_case(using the method for lowering);
2. Fixed some spelling errors in two of the columns;
3. Changed the type of almost all variables so now the dataset consists of **19 categorical (qualitative) variables**, **1 discrete quantitative variable** and **1 datetime variable**.

In [56]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 391979 entries, 0 to 1047937
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   sex                   391979 non-null  category
 1   age                   391979 non-null  int64
 2   classification_final  391979 non-null  category
 3   patient_type          391979 non-null  category
 4   icu                   391979 non-null  category
 5   intubed               391979 non-null  category
 6   pneumonia             391979 non-null  category
 7   pregnant              391979 non-null  category
 8   diabetes              391979 non-null  category
 9   copd                  391979 non-null  category
 10  asthma                391979 non-null  category
 11  inmsupr               391979 non-null  category
 12  hypertension          391979 non-null  category
 13  cardiovascular        391979 non-null  category
 14  renal_chronic         391979 non-null  category
 15  other_disease         391979 non-null  category
 16  obesity               391979 non-null  category
 17  tobacco               391979 non-null  category
 18  usmer                 391979 non-null  category
 19  medical_unit          391979 non-null  category
 20  date_died             54236 non-null   datetime64[ns]
dtypes: category(19), datetime64[ns](1), int64(1)
memory usage: 16.1 MB

In [57]:
covid_data.to_csv("data/covid_data_preprocessed.csv", index=False)

In [58]:
dtypes_dict = covid_data.dtypes.apply(lambda x: x.name).to_dict()
with open("data/covid_data_dtypes.json", "w") as f:
    json.dump(dtypes_dict, f)

## Questions

### Question 1: What comorbiditis have had those who died from COVID?

In [61]:
# Избираме всички редове и колоните от индекс 7 до 18 (последната граница е exclusive, затова слагаме 19)
covid_victims_selected = covid_victims.iloc[:, 7:19]
covid_victims_selected

,pregnant,diabetes,copd,asthma,inmsupr,hypertension,cardiovascular,renal_chronic,other_disease,obesity,tobacco,usmer
0,No,No,No,No,No,Yes,No,No,No,No,No,No
2,Unknown,Yes,No,No,No,No,No,No,No,No,No,No
4,Unknown,Yes,No,No,No,Yes,No,No,No,No,No,No
336,Unknown,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes
337,Unknown,No,No,No,No,No,No,No,No,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...
1047634,No,No,No,No,No,Yes,No,No,No,No,No,Yes
1047635,Unknown,No,No,No,No,Yes,No,No,No,Yes,No,Yes
1047636,Unknown,No,Yes,No,No,Yes,No,No,No,No,No,Yes
1047637,No,No,No,No,No,No,No,No,No,No,No,Yes
1047638,Unknown,No,No,No,No,No,No,No,No,Yes,No,Yes

In [69]:
conditions = [
    "pneumonia",
    "pregnant",
    "diabetes",
    "copd",
    "asthma",
    "inmsupr",
    "hypertension",
    "cardiovascular",
    "renal_chronic",
    "other_disease",
    "obesity",
    "tobacco"
]

# Melt
covid_long = covid_victims.melt(
    id_vars=["sex", "age", "classification_final", "patient_type", "icu", "intubed", "usmer", "medical_unit", "date_died"],  
    value_vars=conditions,  
    var_name="condition",  
    value_name="status"
)

print(covid_long.head())

  sex  age classification_final  patient_type      icu  intubed usmer  \
0   f   65           Mild COVID     Sent home  Unknown  Unknown    No
1   m   55           Mild COVID  Hospitalized       No      Yes    No
2   m   68           Mild COVID     Sent home  Unknown  Unknown    No
3   m   47           Mild COVID  Hospitalized       No       No   Yes
4   m   43           Mild COVID  Hospitalized       No       No    No

  medical_unit  date_died  condition status
0            1 2020-03-05  pneumonia    Yes
1            1 2020-09-06  pneumonia     No
2            1 2020-06-21  pneumonia     No
3            3 2020-03-28  pneumonia    Yes
4            3 2020-03-29  pneumonia    Yes